<script setup lang="ts">
import {onMounted,ref} from 'vue';import {useCommerce} from '../lib/commerce';import {t} from '../i18n';import '../commerce.css';
const {read,api,busy,error,notice}=useCommerce(),settings=ref({sales:false,redemption:true,tickets:true,currency:'CNY',payment_provider:'manual',payment_webhook_url:'',mail_provider:'none',mail_from:'',mail_webhook_url:''}),password=ref('');
onMounted(async()=>{const v=await read<typeof settings.value>('/settings');if(v)settings.value=v});
async function save(){busy.value=true;error.value='';try{await api('/settings','POST',{settings:settings.value,password:password.value});notice.value=t('账户服务设置已保存')}catch(e){error.value=t((e as Error).message)}finally{password.value='';busy.value=false}}
</script>
<template>
<form class="commerce-page settings-card commerce-preferences" @submit.prevent="save">
 <header><div><h2>{{t('账户服务')}}</h2><p>{{t('管理充值、工单以及后续支付和邮件接入')}}</p></div><a href="#/shop">{{t('套餐上架')}} →</a></header>
 <p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
 <div class="commerce-service-options"><label class="inline-check"><input v-model="settings.redemption" type="checkbox"/>{{t('开放兑换码充值')}}</label><label class="inline-check"><input v-model="settings.tickets" type="checkbox"/>{{t('允许成员提交工单')}}</label></div><small class="commerce-muted">{{t('实际是否可购买由“套餐上架”页面中的上架状态决定。')}}</small>
 <details class="integration-settings"><summary>{{t('支付与邮件接入')}}</summary><p>{{t('当前只保存接入配置，不会主动调用外部支付或邮件服务。')}}</p><div class="integration-grid"><section><h3>{{t('支付方式')}}</h3><label>{{t('支付方式')}}<select v-model="settings.payment_provider"><option value="manual">{{t('站内余额 / 手动')}}</option><option value="webhook">{{t('Webhook 预留')}}</option></select></label><label>{{t('支付回调地址')}}<input v-model="settings.payment_webhook_url" type="url" placeholder="https://example.com/payment/webhook"/></label></section><section><h3>{{t('邮件服务')}}</h3><label>{{t('邮件服务')}}<select v-model="settings.mail_provider"><option value="none">{{t('暂不接入')}}</option><option value="webhook">{{t('Webhook 预留')}}</option></select></label><label>{{t('发件人地址')}}<input v-model="settings.mail_from" type="email" placeholder="noreply@example.com"/></label><label>{{t('邮件回调地址')}}<input v-model="settings.mail_webhook_url" type="url" placeholder="https://example.com/mail/webhook"/></label></section></div></details>
 <footer class="commerce-settings-save"><label>{{t('管理员当前密码')}}<input v-model="password" type="password" autocomplete="current-password" required/></label><button class="primary" :disabled="busy">{{t('保存账户服务设置')}}</button></footer>
</form>
</template>
<style scoped>
.commerce-preferences{gap:16px}.commerce-preferences header{align-items:center;margin:0;justify-content:space-between}.commerce-preferences header a{font-size:12px;color:var(--accent-text);white-space:nowrap}.commerce-service-options{display:flex;gap:25px;flex-wrap:wrap}.commerce-service-options .inline-check{flex-direction:row;margin:0;gap:8px}.commerce-service-options input{width:16px;min-height:16px;height:16px}.integration-settings{border-top:1px solid var(--border);border-bottom:1px solid var(--border);padding:18px 0}.integration-settings summary{cursor:pointer;font-size:14px;color:var(--secondary)}.integration-grid{display:grid;grid-template-columns:1fr 1fr;gap:26px}.integration-grid h3{font-size:12px;margin:20px 0 0;color:var(--muted)}.commerce-settings-save{display:flex;align-items:flex-end;justify-content:space-between;gap:20px}.commerce-settings-save label{max-width:360px;flex:1;margin:0}.commerce-settings-save button{flex-shrink:0}@media(max-width:650px){.integration-grid{grid-template-columns:1fr;gap:0}.commerce-service-options{gap:15px;flex-direction:column}.commerce-settings-save{align-items:stretch;flex-direction:column}.commerce-settings-save label{max-width:none}}
</style>
