<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import QRCode from 'qrcode';
import { Check, Copy, LoaderCircle, RefreshCw } from 'lucide-vue-next';
import { useApi, isCancelled, ApiError } from '../lib/api';
import { operationID, stamp, type Order } from '../lib/commerce';
import { tokenAmount, invoiceStateText, invoiceCanPay, invoiceQR, invoiceOperationID, clearInvoiceOperation, transferStateText, type CryptoTransfer, type CryptoInvoice, type CryptoOptions } from '../lib/cryptoPayments';
import { serialPoll } from '../lib/requests';
import { t } from '../i18n';
import { usePaymentModule } from '../lib/paymentModule';
const {enabled:moduleEnabled}=usePaymentModule();
const props=defineProps<{order:Order;readOnly?:boolean}>(),emit=defineEmits<{updated:[]}>();
const api=useApi('/commerce/crypto'),options=ref<CryptoOptions>(),items=ref<CryptoInvoice[]>([]),selectedID=ref(''),assetID=ref(''),mode=ref<'wallet'|'exchange'>('exchange');
const transfers=ref<CryptoTransfer[]>([]),transfersOpen=ref(false),transfersLoading=ref(false),transfersLoaded=ref(false),transfersError=ref('');
const loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),qr=ref(''),now=ref(Date.now()/1000);
const invoice=computed(()=>items.value.find(i=>i.id===selectedID.value)||items.value[0]);
const asset=computed(()=>options.value?.assets.find(a=>a.id===assetID.value));
const payable=computed(()=>!props.readOnly&&moduleEnabled.value&&!!invoice.value&&invoice.value.asset_id===assetID.value&&props.order.state==='pending'&&invoiceCanPay(invoice.value,now.value));
const remaining=computed(()=>invoice.value?.state==='partial');
const payableAtoms=computed(()=>invoice.value?(remaining.value?invoice.value.remaining_atoms:invoice.value.expected_atoms):'0');
const canChangeAsset=computed(()=>!invoice.value||['expired','superseded'].includes(invoice.value.state)||invoice.value.state==='waiting'&&invoice.value.received_atoms==='0');
const canCreate=computed(()=>!props.readOnly&&moduleEnabled.value&&props.order.state==='pending'&&options.value?.enabled&&asset.value?.available&&(!invoice.value||['expired','superseded'].includes(invoice.value.state)||invoice.value.state==='waiting'&&invoice.value.received_atoms==='0'&&assetID.value!==invoice.value.asset_id));
const qrText=computed(()=>invoice.value&&payable.value?invoiceQR(invoice.value,mode.value):'');
let disposed=false,sequence=0,qrSequence=0,transferSequence=0,pending:{key:string,id:string}|undefined;
function merge(values:CryptoInvoice[]){const before=invoice.value;items.value=[...new Map([...items.value,...values].map(i=>[i.id,i])).values()].sort((a,b)=>b.created-a.created||b.id.localeCompare(a.id));if(!selectedID.value)selectedID.value=items.value.find(i=>i.attempt_id===props.order.payment_attempt_id)?.id||items.value[0]?.id||'';const recovered=items.value.find(i=>i.id===selectedID.value);if(!before&&recovered&&recovered.attempt_id!==props.order.payment_attempt_id)emit('updated');if(before&&values.some(i=>i.id===before.id&&(i.state!==before.state||i.order_state!==before.order_state)))emit('updated');}
async function load(){const current=++sequence;loading.value=true;try{const [o,h]=await Promise.all([api<CryptoOptions>('/options'),api<{items:CryptoInvoice[]}>('/invoices?order_id='+encodeURIComponent(props.order.id))]);if(disposed||current!==sequence)return;options.value=o;merge(h.items);if(invoice.value&&invoice.value.attempt_id===props.order.payment_attempt_id){clearInvoiceOperation(props.order.id);pending=undefined;}if(!assetID.value)assetID.value=invoice.value?.asset_id||o.assets.find(a=>a.available)?.id||o.assets[0]?.id||'';if(transfersOpen.value)void loadTransfers();}catch(reason){if(!disposed&&current===sequence&&!isCancelled(reason))error.value=t((reason as Error).message)}finally{if(current===sequence)loading.value=false}}
async function create(){if(busy.value||!canCreate.value)return;busy.value=true;error.value='';notice.value='';const key=props.order.id+':'+assetID.value;if(pending?.key!==key)pending={key,id:invoiceOperationID(props.order.id,assetID.value,operationID)};try{const result=await api<CryptoInvoice>('/invoices','POST',{order_id:props.order.id,asset_id:assetID.value,operation_id:pending.id});if(disposed)return;merge([result]);selectedID.value=result.id;clearInvoiceOperation(props.order.id);pending=undefined;emit('updated');notice.value=t('专属付款地址已准备好，请核对网络后转账。');}catch(reason){if(!disposed&&!isCancelled(reason)){error.value=t((reason as Error).message);if(reason instanceof ApiError&&reason.status<500){clearInvoiceOperation(props.order.id);pending=undefined;}await load()}}finally{busy.value=false}}
async function loadTransfers(){const id=invoice.value?.id;if(!id)return;const current=++transferSequence;transfersLoading.value=true;transfersError.value='';try{const v=await api<CryptoInvoice>('/invoices/'+encodeURIComponent(id));if(!disposed&&current===transferSequence&&invoice.value?.id===id){transfers.value=v.transfers||[];transfersLoaded.value=true}}catch(reason){if(!disposed&&current===transferSequence&&!isCancelled(reason))transfersError.value=t((reason as Error).message)}finally{if(current===transferSequence)transfersLoading.value=false}}
function toggleTransfers(event:Event){transfersOpen.value=(event.target as HTMLDetailsElement).open;if(transfersOpen.value)void loadTransfers()}
function transferAmount(row:CryptoTransfer){const coin=options.value?.assets.find(a=>a.chain_id===row.chain_id&&a.contract.toLowerCase()===row.contract.toLowerCase());if(coin)return tokenAmount(row.atoms,coin.decimals)+' '+coin.symbol;const current=invoice.value;if(current?.chain_id===row.chain_id&&current.contract.toLowerCase()===row.contract.toLowerCase())return tokenAmount(row.atoms,current.decimals)+' '+current.symbol;return row.atoms+' '+t('最小单位')}
watch(selectedID,()=>{transferSequence++;transfers.value=[];transfersLoaded.value=false;transfersLoading.value=false;if(transfersOpen.value)void loadTransfers()});
async function copy(value:string){try{await navigator.clipboard.writeText(value);notice.value=t('已复制')}catch{error.value=t('复制失败，请手动选择内容')}}
watch(qrText,async value=>{const current=++qrSequence;qr.value='';if(!value)return;try{const result=await QRCode.toDataURL(value,{width:240,margin:2,errorCorrectionLevel:'M'});if(!disposed&&current===qrSequence)qr.value=result}catch{if(!disposed&&current===qrSequence)error.value=t('二维码生成失败，可复制地址与金额完成付款')}},{immediate:true});
watch(()=>props.order.id,()=>{sequence++;items.value=[];selectedID.value='';assetID.value='';pending=undefined;error.value='';void load()});
const poll=serialPoll(async()=>{now.value=Date.now()/1000;if(!document.hidden&&!busy.value&&!loading.value)await load()},()=>8000);
onMounted(async()=>{await load();if(!disposed)poll.start()});onUnmounted(()=>{disposed=true;sequence++;qrSequence++;transferSequence++;poll.stop()});
</script>
<template>
<section class="crypto-checkout" :aria-busy="loading||busy">
 <div class="crypto-pay-heading"><h3>{{readOnly?t('加密货币付款记录'):t('加密货币付款')}}</h3><button type="button" :disabled="loading||busy" @click="error='';load()"><RefreshCw :size="15" :class="{spin:loading}"/>{{t('刷新状态')}}</button></div>
 <p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="crypto-pay-note" role="status">{{notice}}</p>
 <template v-if="!readOnly&&moduleEnabled&&props.order.state==='pending'"><label>{{t('付款网络与币种')}}<select v-model="assetID" :disabled="busy||loading||!canChangeAsset"><option v-for="choice in options?.assets" :key="choice.id" :value="choice.id" :disabled="!choice.available">{{choice.name}}{{choice.available?'':' · '+t('暂不可用')}}</option></select></label><p v-if="asset&&!asset.available" class="crypto-pay-note">{{t(asset.unavailable_reason)}}</p><p v-if="!options?.enabled&&!loading" class="crypto-pay-note">{{t('管理员暂未开放加密货币付款')}}</p><button v-if="canCreate" type="button" class="primary" :disabled="busy" @click="create"><LoaderCircle v-if="busy" :size="16" class="spin"/>{{busy?t('正在准备付款地址…'):invoice?t('更换付款网络与地址'):t('获取专属付款地址')}}</button><p v-if="!invoice" class="crypto-pay-note">{{t('选择后才会创建专属地址，付款最终确认后自动开通套餐。')}}</p></template>
 <div v-if="invoice" class="crypto-invoice">
  <div class="crypto-invoice-status" role="status"><Check v-if="invoice.order_state==='completed'" :size="18"/><LoaderCircle v-else-if="invoice.state==='confirming'||invoice.state==='paid'" :size="18" class="spin"/><strong>{{invoiceStateText({...invoice,order_state:props.order.state==='completed'?'completed':invoice.order_state})}}</strong></div>
  <p v-if="invoice.message" class="crypto-pay-note">{{t(invoice.message)}}</p><p v-if="invoice.scan_error" class="error" role="alert">{{t('网络查询暂时不可用，已收到的款项记录会保留，请勿重复付款。')}} {{t(invoice.scan_error)}}</p>
  <dl class="crypto-payment-facts"><div><dt>{{t('付款网络')}}</dt><dd>{{invoice.chain_name}}</dd></div><div><dt>{{t('币种')}}</dt><dd>{{invoice.asset_name}}</dd></div><div><dt>{{remaining?t('还需付款'):t('应付数量')}}</dt><dd><strong>{{tokenAmount(payableAtoms,invoice.decimals,invoice.payment_decimals)}}</strong> {{invoice.symbol}}<button type="button" :aria-label="t('复制应付数量')" @click="copy(tokenAmount(payableAtoms,invoice.decimals,invoice.payment_decimals))"><Copy :size="14"/></button></dd></div><div><dt>{{t('已确认到账')}}</dt><dd>{{tokenAmount(invoice.confirmed_atoms,invoice.decimals)}} {{invoice.symbol}}</dd></div><div v-if="invoice.state==='partial'"><dt>{{t('还需付款')}}</dt><dd>{{tokenAmount(invoice.remaining_atoms,invoice.decimals)}} {{invoice.symbol}}</dd></div></dl>
  <template v-if="payable"><p class="crypto-pay-note">{{t('代币合约')}}<code class="crypto-contract-visible">{{invoice.contract}}</code></p><p class="crypto-network-note">{{t('仅向此地址转入下方指定网络和币种，其他网络或币种不会自动开通。')}}</p><div class="crypto-qr-tabs" role="group" :aria-label="t('转账方式')"><button type="button" :class="{selected:mode==='exchange'}" :aria-pressed="mode==='exchange'" @click="mode='exchange'">{{t('交易所提币')}}</button><button type="button" :class="{selected:mode==='wallet'}" :aria-pressed="mode==='wallet'" @click="mode='wallet'">{{t('钱包扫码')}}</button></div><img v-if="qr" :src="qr" width="220" height="220" :alt="mode==='exchange'?t('收款地址二维码'):t('钱包付款二维码')" class="crypto-pay-qr"/><p class="crypto-pay-note">{{mode==='exchange'?t('二维码仅包含收款地址，请在交易所选择相同网络并填写应付数量。'):t('二维码包含网络、币种与金额，请在钱包内核对后确认转账。')}}</p></template>
  <label>{{t('此订单的收款地址')}}<div class="crypto-copy-field"><input :value="invoice.address" readonly spellcheck="false"/><button type="button" :aria-label="t('复制地址')" @click="copy(invoice.address)"><Copy :size="16"/></button></div></label>
  <p v-if="invoice.state==='confirming'" class="crypto-pay-note">{{t('已检测到转账，正在等待网络最终确认。请勿再次转账。')}}</p><p v-if="!readOnly&&!payable&&!['confirming','paid'].includes(invoice.state)&&invoice.order_state!=='completed'" class="crypto-pay-note">{{t('请勿继续向这张付款单转账。历史地址仍会保留，有款项到账可联系管理员核对。')}}</p><p v-if="invoice.overpaid_atoms&&invoice.overpaid_atoms!=='0'" class="crypto-pay-note">{{t('多付款项')}} {{tokenAmount(invoice.overpaid_atoms,invoice.decimals)}} {{invoice.symbol}} · {{t('请联系管理员处理，不影响已开通套餐。')}}</p>
  <details class="crypto-invoice-detail"><summary>{{t('付款详情')}}</summary><p>{{t('报价有效至')}} {{stamp(invoice.expires)}}</p><p>{{t('手动汇率')}} · 1 {{invoice.symbol}} = ¥{{invoice.cny_per_token}}</p><p>{{t('汇率更新时间')}} {{stamp(invoice.rate_updated_at)}}</p><p>{{t('代币合约')}}<code>{{invoice.contract}}</code></p><p>{{t('最近查询')}} {{invoice.last_scan?stamp(invoice.last_scan):t('等待首次查询')}}</p><p class="commerce-id">{{invoice.id}}</p></details><details class="crypto-invoice-detail crypto-transfers" @toggle="toggleTransfers"><summary>{{t('链上转账记录')}}</summary><p v-if="transfersLoading&&!transfersLoaded" role="status">{{t('正在读取转账记录…')}}</p><p v-if="transfersError" class="error" role="alert">{{transfersError}}</p><p v-if="transfersLoaded&&!transfers.length">{{t('暂未检测到链上转账')}}</p><p v-if="transfers.length>=100">{{t('当前显示最近 100 条转账记录。')}}</p><article v-for="row in transfers" :key="row.chain_id+':'+row.tx_hash+':'+row.log_index"><strong>{{transferAmount(row)}}</strong><span>{{transferStateText(row.state)}}</span><p v-if="row.reason">{{t(row.reason)}}</p><p>{{t('网络编号')}} {{row.chain_id}} · {{stamp(row.block_time)}}</p><p>{{t('代币合约')}}<code>{{row.contract}}</code></p><p>{{t('交易哈希')}}<code>{{row.tx_hash}}</code></p></article><button v-if="transfersLoaded" type="button" :disabled="transfersLoading" @click="loadTransfers">{{t('刷新转账记录')}}</button></details>
 </div>
 <details v-if="items.length>1" class="crypto-invoice-detail"><summary>{{t('历史付款单')}} · {{items.length}}</summary><button v-for="item in items" :key="item.id" type="button" :class="{selected:selectedID===item.id}" @click="selectedID=item.id;assetID=item.asset_id">{{item.chain_name}} · {{item.symbol}} · {{stamp(item.created)}} · {{invoiceStateText(item)}}</button></details>
</section>
</template>
<style scoped>
.crypto-checkout{display:grid;gap:16px;min-width:0;padding-top:8px}.crypto-pay-heading{display:flex;align-items:center;justify-content:space-between;gap:10px}.crypto-pay-heading h3{font-size:17px;margin:0}.crypto-pay-heading button{font-size:12px}.crypto-checkout label{font-size:13px;display:grid;gap:8px}.crypto-checkout select,.crypto-checkout input{width:100%;min-width:0;min-height:44px}.crypto-pay-note,.crypto-network-note{font-size:12px;line-height:1.8;color:var(--secondary);margin:0;overflow-wrap:anywhere}.crypto-network-note{background:var(--accent-soft);padding:12px;border-radius:9px;color:var(--text)}.crypto-invoice{display:grid;gap:16px;min-width:0}.crypto-invoice-status{display:flex;gap:9px;align-items:center;padding:14px;border-radius:10px;background:var(--accent-soft);color:var(--accent-text);font-size:14px}.crypto-payment-facts{display:grid;grid-template-columns:1fr 1fr;gap:17px;margin:0}.crypto-payment-facts dt{font-size:12px;color:var(--secondary);margin-bottom:7px}.crypto-payment-facts dd{font-size:14px;margin:0;overflow-wrap:anywhere;line-height:1.7}.crypto-payment-facts dd strong{font-size:20px}.crypto-payment-facts dd button{padding:4px;min-height:28px;margin-left:7px;vertical-align:middle}.crypto-qr-tabs{display:flex;gap:8px}.crypto-qr-tabs button{flex:1;font-size:12px;min-height:42px}.selected{background:var(--accent-soft);color:var(--accent-text);border-color:var(--accent)}.crypto-contract-visible{display:block;overflow-wrap:anywhere;font-size:11px}.crypto-pay-qr{justify-self:center;border-radius:10px;max-width:100%;height:auto}.crypto-copy-field{display:flex;gap:8px;min-width:0}.crypto-copy-field input{font-family:monospace;font-size:12px}.crypto-copy-field button{flex-shrink:0}.crypto-invoice-detail{font-size:12px;color:var(--secondary);line-height:1.8;min-width:0}.crypto-invoice-detail summary{cursor:pointer;min-height:32px}.crypto-invoice-detail code{display:block;overflow-wrap:anywhere}.crypto-invoice-detail>button{display:block;margin-top:8px;width:100%;text-align:left;white-space:normal;line-height:1.8;font-size:12px}.crypto-transfers article{display:grid;gap:6px;padding:14px 0;border-top:1px solid var(--border)}.crypto-transfers article strong{font-size:14px;color:var(--text);overflow-wrap:anywhere}.crypto-transfers article p{margin:0}.crypto-checkout .error{font-size:12px;line-height:1.8}@media(max-width:460px){.crypto-payment-facts{grid-template-columns:1fr}.crypto-pay-heading{align-items:flex-start}.crypto-pay-heading h3{font-size:16px}}
</style>
