<script setup lang="ts">
import { computed, toRaw, watch, ref } from 'vue';
import { Plus, Trash2, X } from 'lucide-vue-next';
import { useApi, isCancelled } from '../lib/api';
import { usePanelContext } from '../composables/panelContext';
import QualityTags from '../QualityTags.vue';
import SpeedMetric from '../SpeedMetric.vue';
import type { Node } from '../types';
import type { ManagedSite } from '../lib/sites';
import { t } from '../i18n';
const props=defineProps<{site:ManagedSite}>();
const emit=defineEmits<{close:[];saved:[]}>();
const api=useApi('/business-sites');
const {state,refresh,bytes}=usePanelContext();
const editing=ref<ManagedSite|null>(null),busy=ref(false),error=ref('');
const members=ref<Record<number,{selected:boolean;gib:number}>>({}),monthlyBudgetGB=ref(0),cooldownHours=ref(24);
const allUsers=computed(()=>state.value?.users||[]);
const pools=computed(()=>(state.value?.ip_pool||[]).filter(p=>p.enabled));
const commandState:Record<string,string>={queued:'排队中',running:'检测中…',succeeded:'已完成',failed:'失败',cancelled:'已取消'};
function close(){if(!busy.value)emit('close');}
function edit(site:ManagedSite){editing.value=structuredClone(toRaw(site));monthlyBudgetGB.value=(site.monthly_budget||0)/1073741824;cooldownHours.value=(site.cooldown_seconds||86400)/3600;if(!editing.value.default_nodes?.length)editing.value.default_nodes=['vless','hy2'].map(protocol=>({id:protocol+'-main',name:protocol.toUpperCase(),exit_id:'',protocol,enabled:true,policy_version:1,rate_milli:1000,group_ids:['default-subsite']}));editing.value.nodes=editing.value.nodes.map(n=>({...n,policy_version:1,rate_milli:n.policy_version?n.rate_milli:1000,group_ids:n.policy_version?n.group_ids:[pools.value.find(p=>p.id===n.exit_id)?.pool_group==='public'?'legacy-public':'legacy-private']}));members.value={};for(const user of allUsers.value){const g=site.grants.find(g=>g.user_id===user.id);members.value[user.id]={selected:!!g,gib:g?g.quota/1073741824:0};}error.value='';}
function addNode(){if(!editing.value||!pools.value.length)return;editing.value.nodes.push({id:'node_'+crypto.randomUUID().slice(0,8),name:'',protocol:'vless',policy_version:1,rate_milli:1000,group_ids:['default-subsite'],exit_id:pools.value[0].id,enabled:true,dns:{mode:'secure',doh:'https://1.1.1.1/dns-query',ipv6:'block'}});}
async function save(){const s=editing.value;if(!s)return;busy.value=true;error.value='';try{if(!Number.isFinite(monthlyBudgetGB.value)||monthlyBudgetGB.value<0||monthlyBudgetGB.value>1073741824||!Number.isFinite(cooldownHours.value)||cooldownHours.value<1||cooldownHours.value>8760)throw new Error(t('子站预算冷却时长无效'));const grants=Object.entries(members.value).filter(([,v])=>v.selected).map(([id,v])=>({user_id:Number(id),quota:Math.round(v.gib*1073741824)}));await api('/'+s.id,'PUT',{name:s.name,group:s.group,enabled:s.enabled,exclusive:s.exclusive,monthly_budget:Math.round(monthlyBudgetGB.value*1073741824),cooldown_seconds:Math.round(cooldownHours.value*3600),revision:s.revision,default_nodes:s.default_nodes,nodes:s.nodes,grants});await refresh();emit("saved");emit("close");}catch(e){if(!isCancelled(e))error.value=(e as Error).message;}finally{busy.value=false;}}
async function detect(n:Node,kind:string){if(!editing.value)return;busy.value=true;error.value='';try{await api('/'+editing.value.id+'/tasks','POST',{kind,node_id:n.id});}catch(e){if(!isCancelled(e))error.value=(e as Error).message;}finally{busy.value=false;}}

watch(()=>props.site,site=>edit(site),{immediate:true});
</script>
<template><Teleport to="body"><div class="message-overlay" @click.self="close">  <form v-if="editing" class="compose-card business-editor" role="dialog" aria-modal="true" :aria-label="t('子站配置')" @submit.prevent="save"><header><h2>{{t('子站配置')}} · {{editing.id}}</h2><button type="button" class="icon" :disabled="busy" @click="close" :aria-label="t('关闭')"><X/></button></header><p v-if="error" class="error" role="alert">{{t(error)}}</p>
   <div class="field-pair"><label>{{t('站点名称')}}<input v-model="editing.name" maxlength="64" required/></label></div>
   <div class="row-actions"><label class="check-label"><input v-model="editing.enabled" type="checkbox"/>{{t('启用站点')}}</label><label class="check-label"><input v-model="editing.exclusive" type="checkbox"/>{{t('独占出口')}}</label></div>
   <section><h3>{{t('成员与额度')}}</h3><p class="field-help">{{t('成员的协议、到期时间与全局权限在成员管理中设置；此处控制该成员能否使用本站以及本站额度。')}}</p><label>{{t('子站每月资源预算（GiB）')}}<input v-model.number="monthlyBudgetGB" type="number" min="0" step="0.01" required/><small>{{t('0 表示不限；达到上限后移除所有成员订阅，冷却结束后自动恢复。')}}</small></label><label>{{t('预算冷却时长（小时）')}}<input v-model.number="cooldownHours" type="number" min="1" max="8760" step="1" required/><small>{{t('共享预算达到上限后，子站节点暂停此时长；节点组归属不会被修改。')}}</small></label><p class="field-help" v-if="editing.monthly_budget">{{t('本月已使用')}} {{bytes(editing.monthly_usage||0)}} / {{bytes(editing.monthly_budget)}}<template v-if="editing.budget_cooldown_until"> · {{t('冷却中，预计')}} {{new Date(editing.budget_cooldown_until*1000).toLocaleString()}} {{t('恢复')}}</template></p><p class="field-help">{{t('额度为本站累计配额用量上限，单位 GiB，已包含节点倍率。0 仅适用于无限配额成员，剩余额度从主控预留。')}}</p><div class="business-members"><div v-for="u in allUsers.filter(user=>members[user.id])" :key="u.id"><label class="check-label"><input v-model="members[u.id].selected" type="checkbox"/>{{u.username}}</label><input v-model.number="members[u.id].gib" :disabled="!members[u.id].selected" type="number" min="0" step="any" :aria-label="u.username+' GiB'"/><small>{{t('已使用')}} {{bytes(editing.usage?.[u.id]?.metered?(editing.usage?.[u.id]?.quota_upload||0)+(editing.usage?.[u.id]?.quota_download||0):(editing.usage?.[u.id]?.upload||0)+(editing.usage?.[u.id]?.download||0))}}</small></div></div></section>
   <section><h3>{{t('默认节点权限与倍率')}}</h3><p class="field-help">{{t('默认直连始终保留，只有所选节点组内的用户能使用。')}}</p><div v-for="n in editing.default_nodes" :key="n.id" class="business-node"><strong>{{n.protocol.toUpperCase()}}</strong><label>{{t('节点倍率')}}<input :value="(n.rate_milli??1000)/1000" @input="n.rate_milli=Math.round(Number(($event.target as HTMLInputElement).value)*1000);n.policy_version=1" type="number" min="0" max="100" step="0.01" required/></label><p class="field-help">{{t('子站节点自动归组，用户使用权限由套餐决定。')}}</p></div></section>
   <section><div class="section-heading"><h3>{{t('附加节点与出口')}}</h3><button type="button" @click="addNode" :disabled="!pools.length||editing.nodes.length>=14"><Plus :size="14"/>{{t('新增节点')}}</button></div><p class="field-help">{{t('默认 VLESS / HY2 直连始终保留，不占用 IP 池。公共出口产生的节点仅出现在公共订阅。')}}</p>
   <div v-for="(n,i) in editing.nodes" :key="n.id" class="business-node"><div class="node-fields"><label>{{t('协议')}}<select v-model="n.protocol"><option value="vless">VLESS</option><option value="hy2">HY2</option></select></label><label>{{t('出口')}}<select v-model="n.exit_id" required><option v-if="!pools.some(p=>p.id===n.exit_id)" :value="n.exit_id">{{t('出口已删除')}}</option><option v-for="p in pools" :key="p.id" :value="p.id">{{p.pool_group==='public'?t('公共'):t('私有')}} · {{p.label||p.name}} · {{p.probe_ip||p.host}}</option></select></label><button class="icon" type="button" :aria-label="t('移除节点')" @click="editing.nodes.splice(i,1)"><Trash2 :size="15"/></button></div><div class="field-pair"><label v-if="n.protocol==='vless'">SNI<input v-model="n.reality_sni" :placeholder="t('使用业务站默认 SNI')"/></label><label>{{t('出口 DNS 防护')}}<select :value="n.dns?.mode||'system'" @change="n.dns=($event.target as HTMLSelectElement).value==='secure'?{mode:'secure',doh:'https://1.1.1.1/dns-query',ipv6:'block'}:{mode:'system'}"><option value="secure">{{t('开启 IPv4 防护并阻止 IPv6')}}</option><option value="system">{{t('常规模式')}}</option></select></label></div><div v-if="n.dns?.mode==='secure'" class="field-pair"><label>DoH<input v-model="n.dns.doh" type="url" required/></label><label>IPv6<select v-model="n.dns.ipv6"><option value="block">{{t('阻止 IPv6')}}</option><option value="allow">{{t('允许 IPv6 经出口')}}</option></select></label></div><label>{{t('节点倍率')}}<input :value="(n.rate_milli??1000)/1000" @input="n.rate_milli=Math.round(Number(($event.target as HTMLInputElement).value)*1000);n.policy_version=1" type="number" min="0" max="100" step="0.01" required/></label><p class="field-help">{{t('子站节点自动归组，用户使用权限由套餐决定。')}}</p><label class="check-label"><input type="checkbox" v-model="n.enabled"/>{{t('启用节点')}}</label></div></section>
   <section v-if="editing.reports?.length"><h3>{{t('节点质量报告')}}</h3><div v-for="n in editing.reports" :key="n.id" class="business-report"><span>{{t(n.name)}} · {{n.protocol.toUpperCase()}}</span><QualityTags :value="n.quality" :name="n.name" read-only/><SpeedMetric :result="n.speed"/><div class="row-actions"><button type="button" :disabled="busy" @click="detect(n,'quality')">{{t('检测质量')}}</button><button type="button" :disabled="busy" @click="detect(n,'speed')">{{t('测速')}}</button><small v-for="cmd in editing.commands?.filter(c=>c.node_id===n.id)" :key="cmd.kind">{{t(cmd.kind==='speed'?'测速':'质量检测')}} · {{t(commandState[cmd.state]||'状态未知')}}</small></div></div></section>
   <p class="field-help">{{t('已有授权按原同步方式生效；移除子站会自动停止下发授权。')}}</p><footer><button type="button" :disabled="busy" @click="close">{{t('取消')}}</button><button class="primary" :disabled="busy">{{t('保存配置')}}</button></footer>
  </form>
</div></Teleport></template>
<style scoped>
.business-page{display:flex;flex-direction:column;gap:24px}.business-tabs{display:flex;gap:24px;border-bottom:1px solid var(--border);padding-bottom:14px}.business-tabs a{font-size:13px;color:var(--muted)}.business-tabs .active{color:var(--accent-text);font-weight:600}.business-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.business-summary>div{display:flex;flex-direction:column;gap:10px;border:1px solid var(--border);border-radius:12px;padding:20px;background:var(--surface)}.business-summary span,small{font-size:11px;color:var(--muted)}.business-summary strong{font-size:23px;font-weight:600}.business-page td small{display:block;margin-top:7px}.row-actions,.section-heading{display:flex;align-items:center;gap:12px}.section-heading{justify-content:space-between}.business-editor{width:min(820px,calc(100vw - 32px));max-height:90dvh;overflow:auto}.field-pair,.node-fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.node-fields{grid-template-columns:110px minmax(0,1fr) 30px;align-items:end}.business-editor section{border-top:1px solid var(--border);padding-top:16px}.business-editor h3{font-size:14px;margin:0 0 14px}.business-members{display:flex;flex-direction:column;gap:10px;max-height:250px;overflow:auto}.business-members>div{display:grid;grid-template-columns:1fr 110px 130px;align-items:center;gap:12px}.business-editor .check-label{display:flex;flex-direction:row;align-items:center;gap:8px;margin:0}.check-label input{width:16px;height:16px}.business-node{border:1px solid var(--border);border-radius:9px;padding:14px;display:flex;flex-direction:column;gap:12px;margin-top:12px}.business-report{font-size:12px;padding:12px 0;display:flex;flex-direction:column;gap:8px}.connect-command{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--surface-muted);border:1px solid var(--border);border-radius:8px;padding:12px;font-size:11px}@media(max-width:700px){.business-summary{grid-template-columns:1fr 1fr}.business-members>div{grid-template-columns:1fr 90px}.business-members small{grid-column:1/-1}.field-pair{grid-template-columns:1fr}}
</style>
