CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, kind TEXT NOT NULL, target TEXT NOT NULL, guard TEXT NOT NULL DEFAULT '', dedup_key TEXT UNIQUE, state TEXT NOT NULL, actor_id INTEGER NOT NULL, created INTEGER NOT NULL, started INTEGER NOT NULL DEFAULT 0, finished INTEGER NOT NULL DEFAULT 0, next_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, error TEXT NOT NULL DEFAULT '', result BLOB);
CREATE INDEX IF NOT EXISTS tasks_due ON tasks(state,next_at,created);
CREATE INDEX IF NOT EXISTS tasks_history ON tasks(finished);
CREATE TABLE IF NOT EXISTS fleet_peers (id TEXT PRIMARY KEY, doc BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS fleet_tokens (id TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, name TEXT NOT NULL, actor_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, scope TEXT NOT NULL, created INTEGER NOT NULL, expires INTEGER NOT NULL, last_used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS core_revisions (id INTEGER PRIMARY KEY, desired INTEGER NOT NULL DEFAULT 0, applied INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'pending', changed INTEGER NOT NULL DEFAULT 0, applied_at INTEGER NOT NULL DEFAULT 0, error TEXT NOT NULL DEFAULT '');
