CREATE TABLE wallet_accounts (user_id INTEGER PRIMARY KEY, available INTEGER NOT NULL DEFAULT 0 CHECK(available>=0), held INTEGER NOT NULL DEFAULT 0 CHECK(held>=0), revision INTEGER NOT NULL DEFAULT 0);
CREATE TABLE money_transactions (id TEXT PRIMARY KEY, event_key TEXT NOT NULL UNIQUE, user_id INTEGER NOT NULL, actor_id INTEGER NOT NULL, wallet_revision INTEGER NOT NULL, kind TEXT NOT NULL, amount INTEGER NOT NULL, available INTEGER NOT NULL, held INTEGER NOT NULL, reason TEXT NOT NULL, reference TEXT NOT NULL, created INTEGER NOT NULL);
CREATE INDEX money_user_page ON money_transactions(user_id,created,id);
CREATE TABLE money_entries (transaction_id TEXT NOT NULL REFERENCES money_transactions(id), account TEXT NOT NULL, amount INTEGER NOT NULL, PRIMARY KEY(transaction_id,account));
CREATE TABLE commerce_requests (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, fingerprint TEXT NOT NULL, response BLOB NOT NULL, created INTEGER NOT NULL);
CREATE TABLE redeem_codes (id TEXT PRIMARY KEY, batch_id TEXT NOT NULL, code_hash TEXT NOT NULL UNIQUE, suffix TEXT NOT NULL, amount INTEGER NOT NULL CHECK(amount>0), expires INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0, redeemed_by INTEGER NOT NULL DEFAULT 0, redeemed_at INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL, actor_id INTEGER NOT NULL, note TEXT NOT NULL);
CREATE INDEX redeem_codes_page ON redeem_codes(created,id);
CREATE TABLE redeem_attempts (user_id INTEGER NOT NULL, bucket INTEGER NOT NULL, attempts INTEGER NOT NULL, PRIMARY KEY(user_id,bucket));
CREATE TABLE commerce_offers (id TEXT PRIMARY KEY, version INTEGER NOT NULL, enabled INTEGER NOT NULL, doc BLOB NOT NULL);
CREATE TABLE commerce_orders (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, state TEXT NOT NULL, created INTEGER NOT NULL, updated INTEGER NOT NULL, expires INTEGER NOT NULL, doc BLOB NOT NULL);
CREATE INDEX commerce_order_page ON commerce_orders(user_id,created,id);
CREATE UNIQUE INDEX commerce_order_active ON commerce_orders(user_id) WHERE state IN ('pending','provisioning','refunding');
CREATE TABLE commerce_events (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, body TEXT NOT NULL, notified INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE TABLE support_tickets (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, state TEXT NOT NULL, created INTEGER NOT NULL, updated INTEGER NOT NULL, doc BLOB NOT NULL);
CREATE INDEX support_ticket_page ON support_tickets(user_id,updated,id);
CREATE TABLE support_replies (id TEXT PRIMARY KEY, ticket_id TEXT NOT NULL REFERENCES support_tickets(id), user_id INTEGER NOT NULL, internal INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL, doc BLOB NOT NULL);
CREATE INDEX support_reply_page ON support_replies(ticket_id,created,id);
CREATE TABLE support_attachments (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, ticket_id TEXT NOT NULL DEFAULT '', reply_id TEXT NOT NULL DEFAULT '', internal INTEGER NOT NULL DEFAULT 0, size INTEGER NOT NULL, mime TEXT NOT NULL, created INTEGER NOT NULL, expires INTEGER NOT NULL, body BLOB NOT NULL);
CREATE INDEX support_attachment_owner ON support_attachments(user_id,expires);
CREATE TABLE archived_users (user_id INTEGER PRIMARY KEY, created INTEGER NOT NULL);
CREATE UNIQUE INDEX money_wallet_revision ON money_transactions(user_id,wallet_revision);
CREATE INDEX money_entries_account ON money_entries(account);
CREATE TABLE support_upload_attempts (user_id INTEGER NOT NULL, bucket INTEGER NOT NULL, attempts INTEGER NOT NULL, PRIMARY KEY(user_id,bucket));
