<script setup lang="ts">
import {onMounted,onUnmounted,ref,watch} from 'vue';import {usePanelContext} from '../composables/panelContext';import {useCommerce,money,stamp,stateText,type Order} from '../lib/commerce';import {bytes} from '../lib/format';import {serialPoll} from '../lib/requests';import {t} from '../i18n';import '../commerce.css';
const {owner,state}=usePanelContext(),{read,run,busy,error,notice}=useCommerce(),items=ref<Order[]>([]),all=ref(false),refundID=ref(''),password=ref('');
let sequence=0;async function load(){const current=++sequence;const v=await read<{items:Order[]}>('/orders'+(all.value?'?all=1':''));if(v&&current===sequence)items.value=v.items}
async function more(){const current=sequence,last=items.value.at(-1);if(!last)return;const v=await read<{items:Order[]}>('/orders?before='+encodeURIComponent(last.id)+(all.value?'&all=1':''));if(v&&current===sequence)items.value.push(...v.items)}
async function action(o:Order,action:string){const v=await run<Order>('/orders/action',{id:o.id,action,...(action==='refund'?{password:password.value}:{})});if(action==='refund')password.value='';if(v){refundID.value='';notice.value=t('订单状态已更新');await load()}}
async function copy(id:string){try{await navigator.clipboard.writeText(id);notice.value=t('单号已复制')}catch{error.value=t('复制失败，请手动选择单号')}}
const poll=serialPoll(async()=>{if(!document.hidden&&!busy.value&&items.value.some(o=>['pending','provisioning','refunding'].includes(o.state)))await load()},()=>10000);
watch(all,load);onMounted(async()=>{await load();poll.start()});onUnmounted(()=>poll.stop());
</script>
<template><section class="commerce-page"><p v-if="error" class="error commerce-alert" role="alert">{{error}}</p><p v-if="notice" class="commerce-alert" role="status">{{notice}}</p><div class="commerce-actions"><label v-if="owner" class="inline-check"><input v-model="all" type="checkbox"/>{{t('查看全部成员订单')}}</label><button @click="load">{{t('刷新')}}</button></div><div v-if="!items.length" class="commerce-empty">{{t('暂无订单')}}</div>
 <article v-for="o in items" :key="o.id" class="commerce-card"><div class="commerce-line"><h2>{{o.offer.plan.name}}</h2><span :class="['commerce-badge',o.state]">{{stateText(o.state)}}</span><strong class="commerce-amount">{{money(o.offer.price)}}</strong></div><div class="commerce-line"><span class="commerce-id">{{o.id}}</span><button @click="copy(o.id)">{{t('复制单号')}}</button></div><p class="commerce-muted">{{stamp(o.created)}} · {{o.action==='renew'?t('套餐续费'):t('套餐开通')}} · {{t('用户')}} #{{o.user_id}}</p><dl class="commerce-catalog-dl"><div><dt>{{t('套餐版本')}}</dt><dd>v{{o.offer.plan.version}}</dd></div><div><dt>{{t('有效天数')}}</dt><dd>{{o.offer.plan.valid_days||t('不限')}}</dd></div><div><dt>{{t('周期额度')}}</dt><dd>{{o.offer.plan.quota?bytes(o.offer.plan.quota):t('不限')}}</dd></div></dl>
 <p v-if="o.state==='pending'" class="commerce-preview">{{t('确认后冻结对应余额，开通成功后扣减。')}} {{t('订单有效至')}} {{stamp(o.expires)}}</p><p v-if="o.action==='renew'" class="commerce-muted">{{t('续费只延长有效期，不清空当前周期用量。')}}</p><p v-if="o.message" class="commerce-muted">{{t(o.message)}}</p><p v-if="o.state==='completed'" class="commerce-muted">{{t('业务站同步可能稍有延迟，请在订阅中查看已生效节点。')}}</p>
 <div class="commerce-actions"><button v-if="o.state==='pending'&&o.user_id===state?.me.id" class="primary" :disabled="busy" @click="action(o,'confirm')">{{t('确认使用余额')}}</button><button v-if="['pending','provisioning'].includes(o.state)" :disabled="busy" @click="action(o,'cancel')">{{t('取消订单')}}</button><button v-if="owner&&o.state==='completed'" @click="refundID=o.id">{{t('审核整单退款')}}</button><RouterLink :to="{path:'/tickets',query:{order:o.id}}">{{t('订单工单')}}</RouterLink></div>
 <form v-if="refundID===o.id" class="commerce-preview" @submit.prevent="action(o,'refund')"><p>{{t('系统先撤回对应权益，再将订单金额退回用户余额。后续权益有变化时不能自动退款。')}}</p><label>{{t('管理员当前密码')}}<input v-model="password" type="password" autocomplete="current-password" required/></label><div class="commerce-actions"><button :disabled="busy">{{t('确认退款')}}</button><button type="button" @click="refundID=''">{{t('取消')}}</button></div></form></article><button v-if="items.length>=50" @click="more">{{t('加载更多')}}</button>
</section></template>
