<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { ArrowRight, CircleCheck, Copy, CreditCard, FileText, LoaderCircle, RefreshCw, ShoppingBag } from 'lucide-vue-next';
import { usePanelContext } from '../composables/panelContext';
import { useCommerce, money, stamp, stateText, type Order, type PaymentMethod } from '../lib/commerce';
import { bytes } from '../lib/format';
import { serialPoll } from '../lib/requests';
import { t } from '../i18n';
import '../commerce.css';
import '../styles/member-ui.css';
const {owner,state}=usePanelContext(),{read,run,busy,error,notice}=useCommerce(),items=ref<Order[]>([]),methods=ref<PaymentMethod[]>([]),paymentChoice=ref<Record<string,string>>({}),all=ref(false),refundID=ref(''),password=ref(''),loading=ref(true),loadingMore=ref(false),hasMore=ref(false),filter=ref('all'),acting=ref('');
const filters=[{id:'all',label:'全部订单'},{id:'pending',label:'待处理'},{id:'completed',label:'已完成'},{id:'refund',label:'退款'}];
const visible=computed(()=>items.value.filter(o=>filter.value==='all'||(filter.value==='pending'?['pending','provisioning'].includes(o.state):filter.value==='refund'?['refund_requested','refunding','refunded'].includes(o.state):o.state==='completed')));
let sequence=0;
async function load(manual=false){const current=++sequence;if(manual){loading.value=true;error.value=''}try{const v=await read<{items:Order[]}>('/orders'+(all.value?'?all=1':''));if(v&&current===sequence){items.value=v.items;hasMore.value=v.items.length>=50}}finally{if(current===sequence)loading.value=false}}
async function loadMethods(){const v=await read<{items:PaymentMethod[]}>('/payment-methods');if(v){methods.value=v.items.filter(m=>m.enabled&&m.checkout);for(const o of items.value)if(!paymentChoice.value[o.id]&&methods.value[0])paymentChoice.value[o.id]=methods.value[0].id}}
async function more(){const current=sequence,last=items.value.at(-1);if(!last||loadingMore.value)return;loadingMore.value=true;try{const v=await read<{items:Order[]}>('/orders?before='+encodeURIComponent(last.id)+(all.value?'&all=1':''));if(v&&current===sequence){items.value.push(...v.items);hasMore.value=v.items.length>=50}}finally{loadingMore.value=false}}
async function action(o:Order,action:string){acting.value=o.id;try{const v=await run<Order>('/orders/action',{id:o.id,action,...(action==='refund'?{password:password.value}:{})});if(action==='refund')password.value='';if(v){refundID.value='';notice.value=t('订单状态已更新');await load()}}finally{acting.value=''}}
async function pay(o:Order){const method=paymentChoice.value[o.id]||methods.value[0]?.id;if(!method){error.value=t('当前没有可用的在线支付方式');return}acting.value=o.id;try{const v=await run<{attempt:{id:string;state:string};checkout_url:string}>('/orders/pay',{order_id:o.id,payment_method:method});if(v){if(v.checkout_url)window.open(v.checkout_url,'_blank','noopener,noreferrer');notice.value=t('已创建在线支付，请在新窗口完成付款');await load()}}finally{acting.value=''}}
async function copy(id:string){try{await navigator.clipboard.writeText(id);notice.value=t('单号已复制')}catch{error.value=t('复制失败，请手动选择单号')}}
const poll=serialPoll(async()=>{if(!document.hidden&&!busy.value&&!loading.value&&!loadingMore.value&&items.value.some(o=>['pending','provisioning','refund_requested','refunding'].includes(o.state)))await load()},()=>10000);
watch(all,()=>{items.value=[];hasMore.value=false;refundID.value='';password.value='';void load(true)});onMounted(async()=>{await load();await loadMethods();poll.start()});onUnmounted(()=>poll.stop());
</script>
<template>
  <section class="commerce-page member-page orders-page" :aria-busy="loading">
    <header class="member-heading"><div><span class="member-eyebrow"><FileText :size="14"/>ORDERS & SERVICE</span><h1>{{owner?t('订单管理'):t('我的订单')}}</h1><p>{{t('查看开通进度、完成付款或申请售后。')}}</p></div><div class="member-actions"><RouterLink to="/shop"><ShoppingBag :size="16"/>{{owner?t('套餐上架'):t('购买套餐')}}<ArrowRight :size="16"/></RouterLink></div></header>
    <p v-if="error" class="error member-feedback" role="alert">{{error}}</p><p v-if="notice" class="member-feedback" role="status"><CircleCheck :size="17"/>{{notice}}</p>
    <div class="member-toolbar"><div class="member-tabs" role="group" :aria-label="t('订单状态')"><button v-for="f in filters" :key="f.id" :aria-pressed="filter===f.id" @click="filter=f.id">{{t(f.label)}}</button></div><div class="member-actions"><label v-if="owner" class="inline-check"><input v-model="all" :disabled="busy" type="checkbox"/>{{t('查看全部成员订单')}}</label><button :disabled="loading||busy" @click="load(true)"><RefreshCw :size="16" :class="{spin:loading}"/>{{t('刷新')}}</button></div></div>
    <div v-if="loading&&!items.length" class="member-empty" role="status"><LoaderCircle :size="24" class="spin"/><p>{{t('正在加载记录…')}}</p></div>
    <div v-else-if="!visible.length&&!error" class="member-empty"><FileText :size="30"/><h2>{{items.length?t('当前筛选下暂无订单'):t('暂无订单')}}</h2><p>{{t('购买套餐后，可在这里完成付款并查看开通结果。')}}</p><button v-if="filter!=='all'" @click="filter='all'">{{t('全部订单')}}</button><RouterLink v-else class="member-link" to="/shop">{{owner?t('套餐上架'):t('购买套餐')}}<ArrowRight :size="16"/></RouterLink></div>
    <article v-for="o in visible" :key="o.id" class="member-panel order-card">
      <header class="order-heading"><div><div class="order-kind">{{o.action==='renew'?t('套餐续费'):t('套餐开通')}}<span v-if="owner"> · {{t('用户')}} #{{o.user_id}}</span></div><h2>{{o.offer.plan.name}}</h2></div><span :class="['member-status',o.state]"><LoaderCircle v-if="acting===o.id||['provisioning','refunding'].includes(o.state)" :size="13" :class="{spin:acting===o.id}"/>{{stateText(o.state)}}</span><strong class="order-amount">{{money(o.offer.price)}}</strong></header>
      <div class="order-id"><span>{{stamp(o.created)}}</span><span class="commerce-id">{{o.id}}</span><button class="icon" :aria-label="t('复制单号')" :title="t('复制单号')" @click="copy(o.id)"><Copy :size="15"/></button></div>
      <dl class="member-facts order-facts"><div><dt>{{t('有效期')}}</dt><dd>{{o.offer.plan.valid_days?o.offer.plan.valid_days+' '+t('天'):t('永久有效')}}</dd></div><div><dt>{{t('周期额度')}}</dt><dd>{{o.offer.plan.quota?bytes(o.offer.plan.quota):t('不限')}}</dd></div><div v-if="owner"><dt>{{t('套餐版本')}}</dt><dd>v{{o.offer.plan.version}}</dd></div></dl>
      <div v-if="o.state==='pending'" class="member-hint order-notice"><CreditCard :size="18"/><p>{{o.payment_attempt_id?t('在线支付已创建，请完成支付。'):t('确认后冻结对应余额，开通成功后扣减。')}}<br/>{{t('订单有效至')}} {{stamp(o.expires)}}</p></div>
      <p v-if="o.action==='renew'" class="member-label">{{t('续费只延长有效期，不清空当前周期用量。')}}</p><p v-if="o.message" class="member-hint order-message">{{t(o.message)}}</p>
      <div v-if="o.state==='completed'" class="member-hint order-notice"><CircleCheck :size="18"/><p>{{t('套餐已生效，订阅节点会随后台同步更新。')}} <RouterLink to="/subscription">{{t('查看当前套餐与订阅')}} →</RouterLink></p></div>
      <p v-if="o.state==='refund_requested'" class="member-hint">{{owner?t('用户已提交退款申请，请审核。'):t('退款申请已提交，等待管理员审核。')}}</p>
      <footer class="member-actions order-actions"><template v-if="o.state==='pending'&&o.user_id===state?.me.id"><select v-if="methods.length&&!o.payment_attempt_id" v-model="paymentChoice[o.id]" :aria-label="t('在线支付方式')"><option v-for="m in methods" :key="m.id" :value="m.id">{{m.name}}</option></select><button v-if="methods.length" class="primary" :disabled="busy" @click="pay(o)">{{o.payment_attempt_id?t('继续在线支付'):t('在线支付')}}</button><button v-if="!o.payment_attempt_id" :class="{primary:!methods.length}" :disabled="busy" @click="action(o,'confirm')">{{t('确认使用余额')}}</button></template><button v-if="['pending','provisioning'].includes(o.state)" :disabled="busy" @click="action(o,'cancel')">{{t('取消订单')}}</button><button v-if="!owner&&o.state==='completed'&&o.user_id===state?.me.id" :disabled="busy" @click="action(o,'request_refund')">{{t('申请退款')}}</button><button v-if="owner&&['completed','refund_requested'].includes(o.state)" :disabled="busy" @click="refundID=o.id;password=''">{{o.state==='refund_requested'?t('审核退款申请'):t('审核整单退款')}}</button><RouterLink :to="{path:'/tickets',query:{order:o.id}}">{{t('订单工单')}}<ArrowRight :size="14"/></RouterLink></footer>
      <form v-if="refundID===o.id" class="refund-form" @submit.prevent="action(o,'refund')"><h3>{{t('审核整单退款')}}</h3><p class="member-label">{{t('系统先撤回对应权益，再将订单金额退回用户余额。后续权益有变化时不能自动退款。')}}</p><label>{{t('管理员当前密码')}}<input v-model="password" type="password" autocomplete="current-password" required/></label><div class="member-actions"><button class="danger-button" :disabled="busy">{{t('确认退款')}}</button><button type="button" :disabled="busy" @click="refundID='';password=''">{{t('取消')}}</button></div></form>
    </article>
    <div v-if="hasMore" class="order-pagination"><p class="member-label">{{t('筛选仅作用于已加载订单，可继续加载更多。')}}</p><button :disabled="loadingMore||loading" @click="more"><LoaderCircle v-if="loadingMore" :size="16" class="spin"/>{{loadingMore?t('加载中…'):t('加载更多')}}</button></div>
  </section>
</template>
<style scoped>
.orders-page .inline-check{margin:0}.orders-page .inline-check input{min-height:0}.order-heading{display:flex;align-items:center;gap:16px}.order-heading>div{flex:1;min-width:0}.order-heading h2{margin:5px 0 0;font-size:21px;overflow-wrap:anywhere}.order-kind{font-size:12px;color:var(--secondary)}.order-amount{font-size:26px;font-weight:650;letter-spacing:-.6px;white-space:nowrap;font-variant-numeric:tabular-nums}.order-id{display:flex;align-items:center;gap:8px 16px;flex-wrap:wrap;font-size:12px;color:var(--secondary);padding:15px 0 18px;border-bottom:1px solid var(--border)}.order-id button{min-height:44px;width:44px;height:44px;padding:10px;border:0;background:transparent}.order-facts{grid-template-columns:repeat(3,minmax(0,1fr));padding:22px 0}.order-notice{margin-bottom:16px}.order-notice a{color:var(--accent-text);font-weight:550;text-decoration:none}.order-message{margin-bottom:16px;overflow-wrap:anywhere}.order-actions{padding-top:17px;border-top:1px solid var(--border);margin-top:7px}.order-actions>a{margin-left:auto}.order-actions select{width:auto;max-width:230px}.refund-form{padding:20px;border:1px solid var(--border);border-radius:13px;margin-top:20px;background:var(--surface-raised)}.refund-form h3{font-size:15px;margin:0}.refund-form label{max-width:360px}.order-pagination{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:0 4px}.order-pagination p{margin:0}@media(max-width:650px){.order-heading{flex-wrap:wrap;gap:12px}.order-heading>div{flex-basis:calc(100% - 140px)}.order-amount{font-size:24px;margin-left:auto}.order-facts{grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.order-id{gap:7px 12px}.order-actions>a{margin-left:0}.order-actions select{width:100%;max-width:none}.order-actions button{flex:1}.order-pagination{flex-direction:column;align-items:flex-start}.order-heading h2{font-size:19px}}
</style>
