<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {useRouter} from 'vue-router';import {usePanelContext} from '../composables/panelContext';import {useApi} from '../lib/api';import {useCommerce,cents,money,type Offer} from '../lib/commerce';import {bytes} from '../lib/format';import type {Plan} from '../types';import {t} from '../i18n';import '../commerce.css';
const router=useRouter(),{owner,state}=usePanelContext(),{read,run,api,busy,error}=useCommerce(),panelApi=useApi();
const offers=ref<Offer[]>([]),plans=ref<Plan[]>([]),selected=ref(''),price=ref(''),enabled=ref(true),editing=ref<Offer|null>(null),category=ref('');
const visible=computed(()=>offers.value.filter(v=>(owner.value||v.enabled)&&(!category.value||v.plan.category===category.value))),categories=computed(()=>[...new Set(offers.value.map(v=>v.plan.category).filter(Boolean))]);
async function load(){offers.value=(await read<{items:Offer[]}>('/offers'))?.items||[];if(owner.value){try{plans.value=(await panelApi<{plans:Plan[]}>('/plans')).plans.filter(v=>!v.archived)}catch(e){error.value=(e as Error).message}}}
function edit(o:Offer){editing.value=o;selected.value=o.plan.id;price.value=(Number(o.price)/100).toFixed(2);enabled.value=o.enabled}
async function save(){const p=plans.value.find(v=>v.id===selected.value);if(!p)return;let amount:string;try{amount=cents(price.value)}catch(e){error.value=(e as Error).message;return}busy.value=true;error.value='';try{await api('/offers','POST',{id:editing.value?.id||'',version:editing.value?.version||0,plan_id:p.id,plan_version:p.version,price:amount,enabled:enabled.value});editing.value=null;selected.value='';price.value='';await load()}catch(e){error.value=t((e as Error).message)}finally{busy.value=false}}
async function order(o:Offer){const v=await run('/orders',{offer_id:o.id,offer_version:o.version});if(v)await router.push('/orders')}
onMounted(load);
</script>
<template><section class="commerce-page"><p v-if="error" class="error commerce-alert" role="alert">{{error}}</p><p class="commerce-preview">{{t('使用站内余额购买。创建订单后预览并确认，才会冻结余额。有效期内续费不重置当前周期用量。')}}</p>
 <div class="commerce-actions"><select v-model="category" :aria-label="t('套餐分类')"><option value="">{{t('全部分类')}}</option><option v-for="v in categories" :key="v">{{v}}</option></select><button @click="load">{{t('刷新')}}</button></div>
 <div class="commerce-grid"><article v-for="o in visible" :key="o.id" class="commerce-card"><div class="commerce-line"><h2>{{o.plan.name}}</h2><span class="commerce-badge">{{o.enabled?t('已上架'):t('已下架')}}</span></div><p class="commerce-muted">{{o.plan.category}} · v{{o.plan.version}}</p><p>{{o.plan.description}}</p><div class="commerce-amount">{{money(o.price)}}</div><dl class="commerce-catalog-dl"><div><dt>{{t('有效期')}}</dt><dd>{{o.plan.valid_days?o.plan.valid_days+' '+t('天'):t('永久有效')}}</dd></div><div><dt>{{t('周期额度')}}</dt><dd>{{o.plan.quota?bytes(o.plan.quota):t('不限')}}</dd></div><div><dt>{{t('配额周期')}}</dt><dd>{{o.plan.cycle==='30d'?t('每 30 天'):o.plan.cycle==='month'?t('每自然月'):t('不自动重置')}}</dd></div><div><dt>{{t('节点权限组')}}</dt><dd>{{o.plan.group_ids.length}}</dd></div></dl><div class="commerce-actions"><button class="primary" :disabled="busy||!o.enabled" @click="order(o)">{{state?.me.entitlement?.plan_id===o.plan.id&&state.me.expires>Date.now()/1000?t('创建续费订单'):t('创建开通订单')}}</button><button v-if="owner" @click="edit(o)">{{t('编辑销售配置')}}</button></div></article></div>
 <div v-if="!visible.length" class="commerce-empty">{{t('暂无可购买套餐，请联系管理员')}}</div>
 <form v-if="owner" class="commerce-card" @submit.prevent="save"><h2>{{editing?t('编辑销售配置'):t('新增销售配置')}}</h2><p class="commerce-muted">{{t('商品保存套餐与价格快照。已有订单不随改价变化。')}}</p><label>{{t('套餐')}}<select v-model="selected" :aria-label="t('套餐')" required><option value="" disabled>{{t('选择套餐')}}</option><option v-for="p in plans" :key="p.id" :value="p.id">{{p.name}} · v{{p.version}}</option></select></label><label>{{t('售价 / 元')}}<input v-model="price" inputmode="decimal" required/></label><label class="inline-check"><input v-model="enabled" type="checkbox"/>{{t('上架销售')}}</label><div class="commerce-actions"><button class="primary" :disabled="busy">{{t('保存销售配置')}}</button><button v-if="editing" type="button" @click="editing=null;selected='';price=''">{{t('取消')}}</button></div></form>
</section></template>
