<script setup lang="ts">
import {saveSupportDraft,takeSupportDraft} from '../lib/supportDraft';
import {computed,onMounted,onUnmounted,ref} from 'vue';import {useRoute} from 'vue-router';import {usePanelContext} from '../composables/panelContext';import {useCommerce,stamp,stateText,type Ticket,type TicketReply} from '../lib/commerce';import {serialPoll} from '../lib/requests';import {t} from '../i18n';import '../commerce.css';
const route=useRoute(),{owner,state}=usePanelContext(),{read,run,api,busy,error,notice}=useCommerce('/support');
const items=ref<Ticket[]>([]),ticket=ref<Ticket|null>(null),replies=ref<TicketReply[]>([]),creating=ref(!!route.query.order),title=ref(''),body=ref(''),category=ref(route.query.order?'order':'node'),orderID=ref(String(route.query.order||'')),resource=ref(''),resources=ref<{site_id:string;node_id:string;name:string}[]>([]),internal=ref(false),attachments=ref<string[]>([]),uploading=ref(false),nextState=ref(''),priority=ref('normal');
const conversation=computed(()=>replies.value.slice().reverse());
const imageURL=(id:string)=>'/api/support/attachment?id='+encodeURIComponent(id);
let listSequence=0,detailSequence=0;async function load(){const sequence=++listSequence;const v=await read<{items:Ticket[]}>('/tickets');if(sequence===listSequence&&v)items.value=v.items}
async function detail(id:string){const sequence=++detailSequence;const v=await read<{ticket:Ticket;replies:TicketReply[]}>('/ticket?id='+encodeURIComponent(id));if(v&&sequence===detailSequence){const same=ticket.value?.id===id;ticket.value=v.ticket;replies.value=same?[...new Map([...replies.value,...v.replies].map(row=>[row.id,row])).values()].sort((a,b)=>b.id.localeCompare(a.id)):v.replies;nextState.value=v.ticket.state;priority.value=v.ticket.priority}}
async function open(v:Ticket){if(busy.value||uploading.value)return;ticket.value=null;creating.value=false;body.value='';attachments.value=[];await detail(v.id)}
async function more(){const last=items.value.at(-1);if(!last)return;const v=await read<{items:Ticket[]}>('/tickets?before='+encodeURIComponent(last.id));if(v)items.value.push(...v.items)}
async function older(){const last=replies.value.at(-1);if(!last||!ticket.value)return;const v=await read<{replies:TicketReply[]}>('/ticket?id='+encodeURIComponent(ticket.value.id)+'&before='+encodeURIComponent(last.id));if(v)replies.value.push(...v.replies)}
async function submit(){const [site_id='',node_id='']=resource.value.split('/');const wasCreating=creating.value;const v=wasCreating?await run<Ticket>('/tickets',{title:title.value,body:body.value,category:category.value,order_id:orderID.value,site_id,node_id,attachments:attachments.value}):await run<Ticket>('/reply',{id:ticket.value?.id,body:body.value,internal:internal.value,attachments:attachments.value});if(v){
 // The write is committed when run() resolves. Keep the returned ticket
 // visible even if a follow-up refresh is temporarily unavailable.
 notice.value=t('工单已提交');creating.value=false;ticket.value=v;replies.value=[];nextState.value=v.state;priority.value=v.priority;
 body.value='';title.value='';attachments.value=[];internal.value=false;await detail(v.id);await load();if(wasCreating)resource.value='';
 }}
async function status(){if(!ticket.value)return;busy.value=true;error.value='';try{const v=await api<Ticket>('/state','POST',{id:ticket.value.id,revision:ticket.value.revision,state:nextState.value,priority:priority.value});await detail(v.id);await load()}catch(e){error.value=t((e as Error).message)}finally{busy.value=false}}
const fileData=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error(t('图片读取失败')));reader.readAsDataURL(file)});
async function upload(event:Event){const input=event.target as HTMLInputElement,files=Array.from(input.files||[]);input.value='';if(files.length+attachments.value.length>3){error.value=t('每次最多上传 3 张图片');return}uploading.value=true;error.value='';try{for(const file of files){if(file.size>2*1024*1024||!['image/png','image/jpeg'].includes(file.type)||! /\.(png|jpe?g)$/i.test(file.name))throw new Error(t('仅允许 PNG/JPG 图片，每张最大 2 MiB'));const v=await api<{id:string}>('/upload','POST',{name:file.name,mime:file.type,data:await fileData(file)});attachments.value.push(v.id)}}catch(e){error.value=t((e as Error).message)}finally{uploading.value=false}}
function back(){if(busy.value||uploading.value)return;detailSequence++;ticket.value=null;creating.value=false;body.value='';attachments.value=[]}
function create(){if(busy.value||uploading.value)return;detailSequence++;ticket.value=null;creating.value=true;body.value='';attachments.value=[];title.value=''}
const poll=serialPoll(async()=>{if(document.hidden||busy.value||uploading.value)return;if(ticket.value)await detail(ticket.value.id);else if(!creating.value)await load()},()=>15000);
onMounted(async()=>{const draft=!route.query.order?takeSupportDraft(state.value?.me.id||0):null;if(draft){creating.value=draft.creating;title.value=draft.title;body.value=draft.body;category.value=draft.category;orderID.value=draft.orderID;resource.value=draft.resource;internal.value=draft.internal;attachments.value=draft.attachments;if(draft.ticketID)await detail(draft.ticketID)}await load();resources.value=(await read<{items:typeof resources.value}>('/resources'))?.items||[];poll.start()});onUnmounted(()=>{poll.stop();saveSupportDraft(state.value?.me.id||0,{ticketID:ticket.value?.id||'',creating:creating.value,title:title.value,body:body.value,category:category.value,orderID:orderID.value,resource:resource.value,internal:internal.value,attachments:attachments.value,saved:Date.now()})});
</script>
<template><section class="commerce-page"><p v-if="error" class="error commerce-alert" role="alert">{{error}}</p><p v-if="notice" class="commerce-alert" role="status">{{notice}}</p><div class="commerce-actions"><button v-if="ticket||creating" @click="back">{{t('返回工单列表')}}</button><button class="primary" @click="create">{{t('新建工单')}}</button><button @click="ticket?detail(ticket.id):load()">{{t('刷新')}}</button></div>
 <template v-if="!ticket&&!creating"><div v-if="!items.length" class="commerce-empty">{{t('暂无工单')}}</div><article v-for="v in items" :key="v.id" class="commerce-card"><div class="commerce-line"><h2>{{v.title}}</h2><span :class="['commerce-badge',v.state]">{{stateText(v.state)}}</span></div><p class="commerce-id">{{v.id}}</p><p class="commerce-muted">{{stamp(v.updated)}} · {{t('用户')}} #{{v.user_id}}</p><button @click="open(v)">{{t('查看工单')}}</button></article><button v-if="items.length>=50" @click="more">{{t('加载更多')}}</button></template>
 <template v-if="ticket"><article class="commerce-card"><div class="commerce-ticket-heading"><h2>{{ticket.title}}</h2><span class="commerce-badge">{{stateText(ticket.state)}}</span></div><p class="commerce-id">{{ticket.id}}</p><p class="commerce-muted">{{ticket.resource}}</p><p class="commerce-id">{{ticket.order_id}}</p><form class="commerce-actions" @submit.prevent="status"><label>{{t('工单状态')}}<select v-model="nextState" :aria-label="t('工单状态')"><option value="open">{{t('待处理')}}</option><option v-if="!owner&&!['open','closed'].includes(ticket.state)" :value="ticket.state" disabled>{{stateText(ticket.state)}}</option><template v-if="owner"><option value="processing">{{t('处理中')}}</option><option value="waiting_user">{{t('待用户回复')}}</option><option value="resolved">{{t('已解决')}}</option></template><option value="closed">{{t('已关闭')}}</option></select></label><label v-if="owner">{{t('优先级')}}<select v-model="priority" :aria-label="t('优先级')"><option value="normal">{{t('普通')}}</option><option value="urgent">{{t('紧急')}}</option></select></label><button :disabled="busy">{{t('更新状态')}}</button></form></article><button v-if="replies.length>=50" @click="older">{{t('加载更早回复')}}</button>
 <article v-for="reply in conversation" :key="reply.id" :class="['commerce-card',{'commerce-internal':reply.internal}]"><div class="commerce-line"><strong>{{reply.sender}}</strong><span v-if="reply.internal" class="commerce-badge">{{t('内部备注')}}</span><span class="commerce-muted">{{stamp(reply.created)}}</span></div><p class="commerce-reply">{{reply.body}}</p><div class="commerce-images"><a v-for="id in reply.attachments" :key="id" :href="imageURL(id)" target="_blank" rel="noopener noreferrer"><img :src="imageURL(id)" loading="lazy" :alt="t('工单图片，过期后不可查看')"/></a></div></article></template>
 <form v-if="creating||ticket&&!['closed','resolved'].includes(ticket.state)" class="commerce-card" @submit.prevent="submit"><h2>{{creating?t('新建工单'):t('回复工单')}}</h2><template v-if="creating"><label>{{t('工单标题')}}<input v-model.trim="title" maxlength="120" required/></label><label>{{t('问题分类')}}<select v-model="category" :aria-label="t('问题分类')"><option value="account">{{t('账户与余额')}}</option><option value="order">{{t('订单与套餐')}}</option><option value="node">{{t('节点与线路')}}</option><option value="usage">{{t('用量问题')}}</option><option value="other">{{t('其他')}}</option></select></label><label>{{t('关联订单号（选填）')}}<input v-model.trim="orderID" maxlength="100"/></label><label>{{t('关联节点（选填）')}}<select v-model="resource" :aria-label="t('关联节点（选填）')"><option value="">{{t('不关联节点')}}</option><option v-for="v in resources" :key="v.site_id+'/'+v.node_id" :value="v.site_id+'/'+v.node_id">{{v.name}}</option></select></label></template><label>{{t('问题描述或回复')}}<textarea v-model.trim="body" maxlength="4000" rows="6" required/></label><p class="commerce-muted">{{t('请勿提交密码、完整订阅链接或其他认证密钥')}}</p><label v-if="owner&&!creating" class="inline-check"><input v-model="internal" type="checkbox"/>{{t('内部备注，仅管理员可见')}}</label><label>{{t('PNG/JPG，每张最大 2 MiB，每次最多 3 张')}}<input type="file" accept="image/png,image/jpeg,.png,.jpg,.jpeg" multiple :disabled="busy||uploading||attachments.length>=3" @change="upload"/></label><p class="commerce-muted">{{t('未提交图片 15 分钟后失效，工单关闭后图片保留 90 天')}}</p><div class="commerce-images"><div v-for="(id,index) in attachments" :key="id"><a :href="imageURL(id)" target="_blank" rel="noopener"><img :src="imageURL(id)" :alt="t('待提交图片')"/></a><button type="button" @click="attachments.splice(index,1)">{{t('移除')}}</button></div></div><button class="primary" :disabled="busy||uploading">{{uploading?t('图片处理中…'):busy?t('提交中…'):t('提交工单')}}</button></form>
</section></template>
