<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import PageHeading from '../components/PageHeading.vue';
import { ArrowDownLeft, ArrowUpRight, ArrowRight, CircleCheck, Gift, History, LoaderCircle, LockKeyhole, RefreshCw, WalletCards } from 'lucide-vue-next';
import { usePanelContext } from '../composables/panelContext';
import { useCommerce, money, cents, stamp, stateText, type Wallet, type MoneyTransaction } from '../lib/commerce';
import { t } from '../i18n';
import '../commerce.css';
import '../styles/member-ui.css';
const route=useRoute();
const returnOrder=computed(()=>String(route.query.return_order||''));
const {owner,state}=usePanelContext(),{read,run,busy,error,notice}=useCommerce();
const selected=ref(state.value?.me.id||0),wallet=ref<Wallet|null>(null),items=ref<MoneyTransaction[]>([]),code=ref(''),amount=ref(''),reason=ref(''),kind=ref('credit'),loading=ref(true),loadingMore=ref(false),hasMore=ref(false);
let sequence=0;
async function load(){const current=++sequence,user=selected.value;loading.value=true;error.value='';try{const [w,v]=await Promise.all([read<Wallet>('/wallet?user_id='+user),read<{items:MoneyTransaction[]}>('/transactions?user_id='+user)]);if(current===sequence){if(w)wallet.value=w;if(v){items.value=v.items;hasMore.value=v.items.length>=50}}}finally{if(current===sequence)loading.value=false}}
async function more(){if(!items.value.length||loadingMore.value)return;const current=sequence,user=selected.value;loadingMore.value=true;try{const v=await read<{items:MoneyTransaction[]}>('/transactions?user_id='+user+'&before='+encodeURIComponent(items.value.at(-1)!.id));if(v&&selected.value===user&&current===sequence){items.value.push(...v.items);hasMore.value=v.items.length>=50}}finally{loadingMore.value=false}}
async function redeem(){const v=await run('/redeem',{code:code.value});if(v){code.value='';notice.value=t('兑换成功，余额已到账');const ownID=state.value?.me.id||selected.value;if(selected.value===ownID)await load();else selected.value=ownID}}
async function adjust(){let value:string;try{value=cents(amount.value)}catch(e){error.value=(e as Error).message;return}const v=await run('/adjust',{user_id:selected.value,amount:value,kind:kind.value,reason:reason.value});if(v){amount.value='';reason.value='';notice.value=t('余额调整已完成');await load()}}
watch(selected,()=>{wallet.value=null;items.value=[];hasMore.value=false;void load()});onMounted(load);
</script>
<template>
  <section class="commerce-page member-page wallet-page" :aria-busy="loading">
    <PageHeading :title="owner?t('账户余额'):t('我的钱包')" :description="t('余额与每一笔收支，清晰可查。')" eyebrow="WALLET"><template #actions><RouterLink class="member-link" :to="returnOrder?{path:'/orders',query:{checkout:returnOrder}}:'/orders'">{{returnOrder?t('返回订单付款'):t('我的订单')}}<ArrowRight :size="16"/></RouterLink></template></PageHeading><p v-if="returnOrder" class="member-hint">{{t('充值成功后，返回原订单继续确认付款。')}}</p>
    <p v-if="error" class="error member-feedback" role="alert">{{error}}<button :disabled="loading" @click="load">{{t('重试')}}</button></p><p v-if="notice" class="member-feedback" role="status"><CircleCheck :size="17"/>{{notice}}</p>
    <div class="member-toolbar"><label v-if="owner" class="wallet-member">{{t('查看成员')}}<select v-model.number="selected" :disabled="busy" :aria-label="t('查看成员')"><option v-for="u in state?.users" :key="u.id" :value="u.id">{{u.username}}</option></select></label><span v-else class="member-label">{{state?.me.username}}</span><button :disabled="loading||busy" @click="load"><RefreshCw :size="16" :class="{spin:loading}"/>{{t('刷新')}}</button></div>
    <div class="wallet-balances"><article class="member-panel available-balance"><div class="wallet-balance-icon"><WalletCards :size="22"/></div><span class="member-label">{{t('可用余额')}}</span><div class="member-metric">{{wallet?money(wallet.available):'—'}}</div><RouterLink class="member-link" to="/shop">{{owner?t('套餐上架'):t('购买套餐')}}<ArrowRight :size="16"/></RouterLink></article><article class="member-panel held-balance"><div class="wallet-balance-icon"><LockKeyhole :size="21"/></div><span class="member-label">{{t('冻结余额')}}</span><div class="member-metric">{{wallet?money(wallet.held):'—'}}</div><p class="member-copy">{{t('开通中的订单会暂时冻结对应金额')}}</p></article></div>
    <div class="wallet-forms"><form class="member-panel" @submit.prevent="redeem"><div class="member-panel-title"><div><h2>{{t('兑换码充值')}}</h2><p>{{t('兑换成功后计入当前登录账号余额')}}</p></div><Gift :size="22"/></div><label>{{t('输入兑换码')}}<input v-model.trim="code" maxlength="80" autocomplete="off" autocapitalize="characters" spellcheck="false" required placeholder="GY-XXXXXXXX-XXXXXXXX-XXXXXXXXXX"/></label><button class="primary" :disabled="busy||!code"><LoaderCircle v-if="busy" :size="16" class="spin"/>{{busy?t('处理中…'):t('确认兑换')}}</button></form><form v-if="owner" class="member-panel" @submit.prevent="adjust"><div class="member-panel-title"><div><h2>{{t('人工调整余额')}}</h2><p>{{t('当前管理员会话可直接调整余额，操作会永久记入资金流水')}}</p></div></div><div class="member-form-grid"><label>{{t('操作类型')}}<select v-model="kind" :aria-label="t('操作类型')"><option value="credit">{{t('人工入账')}}</option><option value="gift">{{t('赠送')}}</option><option value="debit">{{t('人工扣减')}}</option></select></label><label>{{t('金额 / 元')}}<input v-model="amount" inputmode="decimal" required placeholder="0.00"/></label></div><label>{{t('调整原因')}}<input v-model.trim="reason" maxlength="500" required/></label><button class="primary" :disabled="busy||loading||!wallet">{{t('确认调整')}}</button></form></div>
    <article class="member-panel wallet-ledger"><div class="member-panel-title"><div><h2>{{t('资金流水')}}</h2><p>{{t('每笔余额变动均保留记录。')}}</p></div><History :size="22"/></div><div v-if="loading&&!items.length" class="member-empty" role="status"><LoaderCircle :size="24" class="spin"/><p>{{t('正在加载记录…')}}</p></div><div v-else-if="!items.length&&!error" class="member-empty"><History :size="28"/><h2>{{t('暂无资金流水')}}</h2><p>{{t('充值或购买套餐后，收支记录会显示在这里。')}}</p></div><div v-else class="transaction-list"><div v-for="row in items" :key="row.id" class="transaction-row"><div class="transaction-icon"><ArrowDownLeft v-if="['credit','gift','redemption','release','refund'].includes(row.kind)" :size="18"/><ArrowUpRight v-else-if="['debit','hold','purchase'].includes(row.kind)" :size="18"/><History v-else :size="18"/></div><div class="transaction-info"><div class="transaction-heading"><strong>{{stateText(row.kind)}}</strong><strong class="transaction-amount">{{money(row.amount)}}</strong></div><div class="transaction-meta"><span>{{stamp(row.created)}}</span><span v-if="row.reason">{{row.reason}}</span></div><details class="transaction-details"><summary>{{t('流水详情')}}</summary><div><p class="commerce-id">{{row.id}}</p><p v-if="row.reference" class="commerce-id">{{row.reference}}</p><p class="member-label">{{t('可用余额')}} {{money(row.available)}} · {{t('冻结余额')}} {{money(row.held)}}</p></div></details></div></div></div><button v-if="hasMore" class="ledger-more" :disabled="loadingMore||loading" @click="more"><LoaderCircle v-if="loadingMore" :size="16" class="spin"/>{{loadingMore?t('加载中…'):t('加载更多')}}</button></article>
  </section>
</template>
<style scoped>
.wallet-page .wallet-member{display:flex;flex-direction:row;align-items:center;gap:14px}.wallet-member select{min-width:200px;width:auto}.wallet-balances{display:grid;grid-template-columns:1.2fr 1fr;gap:20px}.available-balance{background:var(--surface)}.wallet-balances .member-panel{position:relative;padding:28px}.wallet-balance-icon{position:absolute;right:25px;top:27px;display:grid;place-items:center;width:42px;height:42px;border-radius:13px;color:var(--accent-text);background:var(--accent-soft)}.wallet-balances .member-metric{font-size:36px;margin:12px 0 15px}.wallet-balances .member-copy{font-size:13px}.wallet-forms{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,360px),1fr));gap:20px}.wallet-forms .member-panel{display:flex;flex-direction:column;align-items:stretch}.wallet-forms .primary{align-self:flex-start}.wallet-forms input{width:100%;box-sizing:border-box}.wallet-ledger .member-empty{border:0;background:none;min-height:180px}.transaction-row{display:flex;gap:14px;padding:20px 0;border-bottom:1px solid var(--border)}.transaction-row:last-child{border-bottom:0;padding-bottom:0}.transaction-icon{height:38px;width:38px;border-radius:12px;display:grid;place-items:center;color:var(--accent-text);background:var(--accent-soft);flex-shrink:0}.transaction-info{flex:1;min-width:0}.transaction-heading{display:flex;align-items:baseline;justify-content:space-between;gap:15px;font-size:14px;line-height:1.6}.transaction-amount{font-size:17px;font-variant-numeric:tabular-nums;white-space:nowrap}.transaction-meta{display:flex;flex-wrap:wrap;gap:4px 16px;font-size:12px;line-height:1.7;color:var(--secondary);margin:5px 0 9px;overflow-wrap:anywhere}.transaction-details{font-size:12px;color:var(--secondary)}.transaction-details summary{cursor:pointer;width:fit-content;padding:4px 0}.transaction-details>div{padding:10px 14px;margin-top:6px;background:var(--surface-raised);border-radius:10px}.transaction-details p{margin:4px 0}.ledger-more{display:flex;margin:22px auto 0}@media(max-width:700px){.wallet-balances{grid-template-columns:1fr}.wallet-balances .member-panel{padding:23px}.wallet-balances .member-metric{font-size:32px}.wallet-member{max-width:100%;flex-wrap:wrap}.wallet-member select{min-width:0;max-width:100%}.transaction-icon{display:none}.transaction-row{padding:18px 0}}
</style>
