<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import PageHeading from '../components/PageHeading.vue';
import { supportsPaymentPurpose } from '../lib/cryptoPayments';
import { usePaymentModule } from '../lib/paymentModule';
const {enabled:moduleEnabled,error:moduleError,loaded:moduleLoaded,refresh:refreshModule}=usePaymentModule();
import { ArrowDownLeft, ArrowUpRight, ArrowRight, CircleCheck, CreditCard, Gift, History, LoaderCircle, LockKeyhole, RefreshCw, WalletCards } from 'lucide-vue-next';
import { usePanelContext } from '../composables/panelContext';
import { useCommerce, money, cents, stamp, stateText, paymentStateText, canResumePayment, paymentCheckoutURL, preparePaymentWindow, walletRevision, type Wallet, type MoneyTransaction, type PaymentMethod, type PaymentAttempt, type PaymentCheckout } from '../lib/commerce';
import { mergeHistory } from '../components/member/flow';
import { serialPoll } from '../lib/requests';
import { t } from '../i18n';
import '../commerce.css';
import '../styles/member-ui.css';
const route=useRoute();
const returnOrder=computed(()=>String(route.query.return_order||''));
const {owner,state}=usePanelContext(),{read,run,busy,error,notice}=useCommerce();
const selected=ref(state.value?.me.id||0),wallet=ref<Wallet|null>(null),items=ref<MoneyTransaction[]>([]),code=ref(''),amount=ref(''),reason=ref(''),kind=ref('credit'),loading=ref(true),loadingMore=ref(false),hasMore=ref(false);
const methods=ref<PaymentMethod[]>([]),payments=ref<PaymentAttempt[]>([]),topupAmount=ref(''),paymentMethod=ref(''),paymentURL=ref(''),paymentsLoaded=ref(false),methodsLoaded=ref(false),checkingPayments=ref(false);
const ownWallet=computed(()=>selected.value===state.value?.me.id);
const topups=computed(()=>payments.value.filter(p=>p.purpose==='topup'&&p.user_id===selected.value));
const pendingTopups=computed(()=>topups.value.filter(p=>['created','awaiting_customer','paid'].includes(p.state)));
let sequence=0,paymentSequence=0,disposed=false,expanded=false;
async function load(manual=true){const current=++sequence,user=selected.value;if(manual){loading.value=true;error.value=''}try{const [w,v]=await Promise.all([read<Wallet>('/wallet?user_id='+user),read<{items:MoneyTransaction[]}>('/transactions?user_id='+user)]);if(current===sequence&&!disposed){if(w)wallet.value=w;if(v){items.value=mergeHistory(items.value,v.items);if(!expanded)hasMore.value=v.items.length>=50}}}finally{if(current===sequence)loading.value=false}}
async function more(){if(!items.value.length||loadingMore.value)return;const current=sequence,user=selected.value;loadingMore.value=true;try{const v=await read<{items:MoneyTransaction[]}>('/transactions?user_id='+user+'&before='+encodeURIComponent(items.value.at(-1)!.id));if(v&&selected.value===user&&current===sequence&&!disposed){items.value=mergeHistory(items.value,v.items);hasMore.value=v.items.length>=50;expanded=true}}finally{loadingMore.value=false}}
async function redeem(){if(!moduleEnabled.value)return;const v=await run('/redeem',{code:code.value});if(v){code.value='';notice.value=t('兑换成功，余额已到账');const ownID=state.value?.me.id||selected.value;if(selected.value===ownID)await load();else selected.value=ownID}}
async function adjust(){let value:string;try{value=cents(amount.value)}catch(e){error.value=(e as Error).message;return}const v=await run('/adjust',{user_id:selected.value,amount:value,kind:kind.value,reason:reason.value});if(v){amount.value='';reason.value='';notice.value=t('余额调整已完成');await load()}}
async function loadPayments(){const current=++paymentSequence;checkingPayments.value=true;try{const result=await read<{items:PaymentAttempt[]}>('/payments');if(!result||disposed||current!==paymentSequence)return;const completed=result.items.some(p=>p.purpose==='topup'&&p.user_id===state.value?.me.id&&p.state==='completed'&&payments.value.some(old=>old.id===p.id&&old.state!=='completed'));payments.value=result.items;paymentsLoaded.value=true;if(completed){walletRevision.value++;notice.value=t('在线充值已到账');paymentURL.value='';await load(false)}}finally{if(current===paymentSequence)checkingPayments.value=false}}
async function loadMethods(){const result=await read<{items:PaymentMethod[]}>('/payment-methods');if(result&&!disposed){methodsLoaded.value=true;methods.value=result.items.filter(p=>p.enabled&&p.checkout&&!p.archived&&supportsPaymentPurpose(p,'topup'));if(!methods.value.some(p=>p.id===paymentMethod.value))paymentMethod.value=methods.value[0]?.id||''}}
function resume(payment:PaymentAttempt){if(busy.value||!moduleEnabled.value||!ownWallet.value||!canResumePayment(payment)||!payment.checkout_url)return;try{paymentURL.value=paymentCheckoutURL(payment.checkout_url);preparePaymentWindow().open(paymentURL.value);notice.value=t('请在支付页面完成付款，到账后余额会自动更新。')}catch(e){error.value=(e as Error).message}}
async function topup(){
 if(busy.value||!moduleEnabled.value||!ownWallet.value||!paymentMethod.value)return;
 let value:string;try{value=cents(topupAmount.value)}catch(e){error.value=(e as Error).message;return}
 const existing=topups.value.find(p=>p.provider_id===paymentMethod.value&&p.amount===value&&canResumePayment(p)&&p.checkout_url);
 if(existing){resume(existing);return}
 const popup=preparePaymentWindow();paymentURL.value='';
 try{const result=await run<PaymentCheckout>('/wallet/topup',{amount:value,payment_method:paymentMethod.value});if(!result){popup.close();return}payments.value=mergeHistory(payments.value,[result.attempt]);paymentsLoaded.value=true;
  if(canResumePayment(result.attempt)&&result.checkout_url){paymentURL.value=paymentCheckoutURL(result.checkout_url);popup.open(paymentURL.value);notice.value=t('请在支付页面完成付款，到账后余额会自动更新。')}else{popup.close();notice.value=paymentStateText(result.attempt.state);if(result.attempt.state==='completed'){walletRevision.value++;await load(false)}}
  await loadPayments();
 }catch(e){popup.close();error.value=(e as Error).message}
}
async function refreshWallet(){await Promise.all([load(),loadMethods(),loadPayments(),refreshModule()])}
function returnToWallet(){if(!document.hidden&&!busy.value&&!checkingPayments.value&&!disposed){void loadPayments();void load(false)}}
watch(moduleEnabled,enabled=>{if(!enabled)paymentURL.value=''});
watch(selected,()=>{wallet.value=null;items.value=[];hasMore.value=false;expanded=false;paymentURL.value='';void load();void loadPayments()});
const poll=serialPoll(async()=>{if(!document.hidden&&!busy.value&&!checkingPayments.value&&pendingTopups.value.length)await loadPayments()},()=>8000);
onMounted(async()=>{document.addEventListener('visibilitychange',returnToWallet);window.addEventListener('focus',returnToWallet);await Promise.all([load(),loadMethods(),loadPayments(),refreshModule()]);if(!disposed)poll.start()});
onUnmounted(()=>{disposed=true;sequence++;paymentSequence++;poll.stop();document.removeEventListener('visibilitychange',returnToWallet);window.removeEventListener('focus',returnToWallet)});
</script>
<template>
  <section class="commerce-page member-page wallet-page" :aria-busy="loading">
    <PageHeading :title="owner?t('账户余额'):t('我的钱包')" :description="t('余额与每一笔收支，清晰可查。')" eyebrow="WALLET"><template #actions><RouterLink class="member-link" :to="returnOrder?{path:'/orders',query:{checkout:returnOrder}}:'/orders'">{{returnOrder?t('返回订单付款'):t('我的订单')}}<ArrowRight :size="16"/></RouterLink></template></PageHeading><p v-if="returnOrder" class="member-hint">{{t('充值成功后，返回原订单继续确认付款。')}}</p>
    <p v-if="error" class="error member-feedback" role="alert">{{error}}<button :disabled="loading" @click="refreshWallet">{{t('重试')}}</button></p><p v-if="notice" class="member-feedback" role="status"><CircleCheck :size="17"/>{{notice}}</p>
    <p v-if="moduleError" class="error member-feedback" role="alert">{{moduleError}}<button @click="refreshModule">{{t('重试')}}</button></p><p v-else-if="moduleLoaded&&!moduleEnabled" class="member-hint" role="status">{{t('本站支付模块暂未开放，充值已暂停，历史余额与资金流水继续保留。')}}</p>
    <div class="member-toolbar"><label v-if="owner" class="wallet-member">{{t('查看成员')}}<select v-model.number="selected" :disabled="busy" :aria-label="t('查看成员')"><option v-for="u in state?.users" :key="u.id" :value="u.id">{{u.username}}</option></select></label><span v-else class="member-label">{{state?.me.username}}</span><button :disabled="loading||busy" @click="refreshWallet"><RefreshCw :size="16" :class="{spin:loading}"/>{{t('刷新')}}</button></div>
    <div class="wallet-balances"><article class="member-panel available-balance"><div class="wallet-balance-icon"><WalletCards :size="22"/></div><span class="member-label">{{t('可用余额')}}</span><div class="member-metric">{{wallet?money(wallet.available):'—'}}</div><RouterLink class="member-link" to="/shop">{{owner?t('套餐上架'):t('购买套餐')}}<ArrowRight :size="16"/></RouterLink></article><article class="member-panel held-balance"><div class="wallet-balance-icon"><LockKeyhole :size="21"/></div><span class="member-label">{{t('冻结余额')}}</span><div class="member-metric">{{wallet?money(wallet.held):'—'}}</div><p class="member-copy">{{t('使用钱包付款的订单，开通时会暂时冻结对应金额')}}</p></article></div>
    <div class="wallet-forms"><form v-if="ownWallet" class="member-panel online-topup" @submit.prevent="topup"><div class="member-panel-title"><div><h2>{{t('在线充值')}}</h2><p>{{t('充值到当前登录账户，到账后可用余额支付套餐。')}}</p></div><CreditCard :size="22"/></div><template v-if="moduleEnabled&&methods.length"><div class="member-form-grid"><label>{{t('充值金额 / 元')}}<input v-model.trim="topupAmount" inputmode="decimal" placeholder="0.00" required :disabled="busy"/></label><label>{{t('支付方式')}}<select v-model="paymentMethod" :disabled="busy" required><option v-for="method in methods" :key="method.id" :value="method.id">{{method.name}}</option></select></label></div><button class="primary" :disabled="busy||!topupAmount||!paymentMethod"><LoaderCircle v-if="busy" :size="16" class="spin"/>{{busy?t('处理中…'):t('前往支付')}}</button></template><p v-else-if="moduleLoaded&&!moduleEnabled" class="member-label">{{t('充值暂未开放')}}</p><p v-else-if="!moduleLoaded||!methodsLoaded" class="member-label" role="status">{{t('正在读取支付方式…')}}</p><p v-else class="member-label">{{t('管理员暂未启用在线充值，可使用兑换码充值。')}}</p><a v-if="paymentURL" class="member-link" :href="paymentURL" target="_blank" rel="noopener noreferrer">{{t('重新打开支付页面')}}<ArrowRight :size="16"/></a><p class="member-label">{{t('完成支付后自动核对到账；返回本页不会直接增加余额。')}}</p></form><form class="member-panel" @submit.prevent="redeem"><div class="member-panel-title"><div><h2>{{t('兑换码充值')}}</h2><p>{{t('兑换成功后计入当前登录账号余额')}}</p></div><Gift :size="22"/></div><label>{{t('输入兑换码')}}<input v-model.trim="code" maxlength="80" autocomplete="off" autocapitalize="characters" spellcheck="false" required placeholder="GY-XXXXXXXX-XXXXXXXX-XXXXXXXXXX"/></label><button class="primary" :disabled="busy||!moduleEnabled||!code"><LoaderCircle v-if="busy" :size="16" class="spin"/>{{busy?t('处理中…'):t('确认兑换')}}</button></form><form v-if="owner" class="member-panel" @submit.prevent="adjust"><div class="member-panel-title"><div><h2>{{t('人工调整余额')}}</h2><p>{{t('当前管理员会话可直接调整余额，操作会永久记入资金流水')}}</p></div></div><div class="member-form-grid"><label>{{t('操作类型')}}<select v-model="kind" :aria-label="t('操作类型')"><option value="credit">{{t('人工入账')}}</option><option value="gift">{{t('赠送')}}</option><option value="debit">{{t('人工扣减')}}</option></select></label><label>{{t('金额 / 元')}}<input v-model="amount" inputmode="decimal" required placeholder="0.00"/></label></div><label>{{t('调整原因')}}<input v-model.trim="reason" maxlength="500" required/></label><button class="primary" :disabled="busy||loading||!wallet">{{t('确认调整')}}</button></form></div>
    <article v-if="topups.length||!paymentsLoaded" class="member-panel topup-history"><div class="member-panel-title"><div><h2>{{t('在线充值记录')}}</h2><p>{{t('支付进度与到账结果会自动更新。')}}</p></div><button :disabled="checkingPayments||busy" @click="loadPayments"><RefreshCw :size="16" :class="{spin:checkingPayments}"/>{{t('刷新状态')}}</button></div><p v-if="!paymentsLoaded" role="status">{{t('加载中…')}}</p><div v-for="payment in topups" :key="payment.id" class="topup-row"><div><strong>{{money(payment.amount)}}</strong><span class="member-label">{{stamp(payment.created)}} · {{paymentStateText(payment.state)}}</span><p v-if="payment.message" class="member-label">{{t(payment.message)}}</p><p v-if="payment.refund_status" class="member-label">{{t('退款状态')}} · {{paymentStateText(payment.refund_status)}}</p></div><button v-if="moduleEnabled&&ownWallet&&canResumePayment(payment)&&payment.checkout_url" :disabled="busy" @click="resume(payment)">{{t('继续支付')}}<ArrowRight :size="15"/></button></div></article>
    <article class="member-panel wallet-ledger"><div class="member-panel-title"><div><h2>{{t('资金流水')}}</h2><p>{{t('每笔余额变动均保留记录。')}}</p></div><History :size="22"/></div><div v-if="loading&&!items.length" class="member-empty" role="status"><LoaderCircle :size="24" class="spin"/><p>{{t('正在加载记录…')}}</p></div><div v-else-if="!items.length&&!error" class="member-empty"><History :size="28"/><h2>{{t('暂无资金流水')}}</h2><p>{{t('充值或购买套餐后，收支记录会显示在这里。')}}</p></div><div v-else class="transaction-list"><div v-for="row in items" :key="row.id" class="transaction-row"><div class="transaction-icon"><ArrowDownLeft v-if="['credit','gift','redemption','online_topup','release','refund'].includes(row.kind)" :size="18"/><ArrowUpRight v-else-if="['debit','hold','purchase'].includes(row.kind)" :size="18"/><History v-else :size="18"/></div><div class="transaction-info"><div class="transaction-heading"><strong>{{stateText(row.kind)}}</strong><strong class="transaction-amount">{{money(row.amount)}}</strong></div><div class="transaction-meta"><span>{{stamp(row.created)}}</span><span v-if="row.reason">{{row.reason}}</span></div><details class="transaction-details"><summary>{{t('流水详情')}}</summary><div><p class="commerce-id">{{row.id}}</p><p v-if="row.reference" class="commerce-id">{{row.reference}}</p><p class="member-label">{{t('可用余额')}} {{money(row.available)}} · {{t('冻结余额')}} {{money(row.held)}}</p></div></details></div></div></div><button v-if="hasMore" class="ledger-more" :disabled="loadingMore||loading" @click="more"><LoaderCircle v-if="loadingMore" :size="16" class="spin"/>{{loadingMore?t('加载中…'):t('加载更多')}}</button></article>
  </section>
</template>
<style scoped>
.topup-history .member-panel-title button{flex-shrink:0}.topup-row{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 0;border-top:1px solid var(--border)}.topup-row>div{min-width:0}.topup-row strong{display:block;font-size:18px;margin-bottom:7px}.topup-row p{margin:5px 0 0;overflow-wrap:anywhere}.topup-row button{flex-shrink:0}.online-topup .member-link{margin-top:14px}.online-topup select{width:100%;min-width:0}@media(max-width:550px){.topup-row{flex-wrap:wrap}.topup-history .member-panel-title{flex-wrap:wrap}}

.wallet-page .wallet-member{display:flex;flex-direction:row;align-items:center;gap:14px}.wallet-member select{min-width:200px;width:auto}.wallet-balances{display:grid;grid-template-columns:1.2fr 1fr;gap:20px}.available-balance{background:var(--surface)}.wallet-balances .member-panel{position:relative;padding:28px}.wallet-balance-icon{position:absolute;right:25px;top:27px;display:grid;place-items:center;width:42px;height:42px;border-radius:13px;color:var(--accent-text);background:var(--accent-soft)}.wallet-balances .member-metric{font-size:36px;margin:12px 0 15px}.wallet-balances .member-copy{font-size:13px}.wallet-forms{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,360px),1fr));gap:20px}.wallet-forms .member-panel{display:flex;flex-direction:column;align-items:stretch}.wallet-forms .primary{align-self:flex-start}.wallet-forms input{width:100%;box-sizing:border-box}.wallet-ledger .member-empty{border:0;background:none;min-height:180px}.transaction-row{display:flex;gap:14px;padding:20px 0;border-bottom:1px solid var(--border)}.transaction-row:last-child{border-bottom:0;padding-bottom:0}.transaction-icon{height:38px;width:38px;border-radius:12px;display:grid;place-items:center;color:var(--accent-text);background:var(--accent-soft);flex-shrink:0}.transaction-info{flex:1;min-width:0}.transaction-heading{display:flex;align-items:baseline;justify-content:space-between;gap:15px;font-size:14px;line-height:1.6}.transaction-amount{font-size:17px;font-variant-numeric:tabular-nums;white-space:nowrap}.transaction-meta{display:flex;flex-wrap:wrap;gap:4px 16px;font-size:12px;line-height:1.7;color:var(--secondary);margin:5px 0 9px;overflow-wrap:anywhere}.transaction-details{font-size:12px;color:var(--secondary)}.transaction-details summary{cursor:pointer;width:fit-content;padding:4px 0}.transaction-details>div{padding:10px 14px;margin-top:6px;background:var(--surface-raised);border-radius:10px}.transaction-details p{margin:4px 0}.ledger-more{display:flex;margin:22px auto 0}@media(max-width:700px){.wallet-balances{grid-template-columns:1fr}.wallet-balances .member-panel{padding:23px}.wallet-balances .member-metric{font-size:32px}.wallet-member{max-width:100%;flex-wrap:wrap}.wallet-member select{min-width:0;max-width:100%}.transaction-icon{display:none}.transaction-row{padding:18px 0}}
</style>
