<script setup lang="ts">
import { useApi, isCancelled } from "./lib/api";
import { latestRequest } from "./lib/requests";
const api = useApi("/import-sources");
const loadRequest = latestRequest();
import { nextTick, onMounted, onUnmounted, reactive, ref, watch } from 'vue';
import { Plus, RefreshCw, Link2, Pencil, Trash2, Clock3, Database, X, ShieldCheck, LoaderCircle } from 'lucide-vue-next';
import { t, locale } from './i18n';
type Source={id:string;name:string;address:string;enabled:boolean;queued:boolean;revision:string;last_attempt:number;last_success:number;next_at:number;failures:number;error:string;resource_ids:string[];added:number;removed:number;retained:number;warnings:{index:number;reason:string}[]};
type Row={resource_ids:string[];source:Source;running:boolean;resources:number;stale:number};
defineProps<{embedded?:boolean}>();
const emit=defineEmits<{refresh:[];resources:[ids:string[],name:string];loaded:[rows:Row[]]}>();
const rows=ref<Row[]>([]),ready=ref(false),busy=ref(false),error=ref(''),notice=ref(''),editing=ref(false),deleting=ref<Source|null>(null);
const deleteDialog=ref<HTMLElement|null>(null),deleteResult=ref<{resources:number;nodes:number;shared:number}|null>(null);
let deleteTrigger:HTMLElement|null=null;
const form=reactive({id:'',name:'',url:'',enabled:true,revision:''});
const date=(v:number)=>v?new Date(v*1000).toLocaleString(locale.value):t('尚未执行');
async function load(){
 const request=loadRequest.start();
 try{const result=await api('','GET',undefined,{signal:request.signal});if(!loadRequest.isCurrent(request))return;rows.value=result.items;ready.value=true;error.value='';emit('loaded',rows.value);}
 catch(e){if(loadRequest.isCurrent(request)&&!isCancelled(e))error.value=(e as Error).message;}
}
async function action(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';deleteResult.value=null;try{await fn();await load();emit('refresh');}catch(e){if(!isCancelled(e))error.value=(e as Error).message;}finally{busy.value=false;}}
function edit(source?:Source){Object.assign(form,{id:source?.id||'',name:source?.name||'',url:'',enabled:source?.enabled??true,revision:source?.revision||''});editing.value=true;error.value='';}
async function save(){await action(async()=>{await api(form.id?'/'+form.id:'',form.id?'PUT':'POST',{name:form.name,url:form.url,enabled:form.enabled,revision:form.revision});editing.value=false;form.url='';notice.value=form.id?'订阅来源已保存':'订阅来源已保存，首次更新已排队';});}
async function refresh(source:Source){await action(async()=>{await api('/'+source.id+'/refresh','POST',{});notice.value='更新已排队，后台将依次执行';});}
function confirmDelete(source:Source,event:MouseEvent){if(busy.value)return;deleteTrigger=event.currentTarget as HTMLElement;error.value='';deleting.value=source;}
function closeDialog(){if(busy.value)return;editing.value=false;deleting.value=null;}
function deleteKeydown(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();closeDialog();return}if(event.key==='Tab'&&deleteDialog.value){const items=Array.from(deleteDialog.value.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));if(!items.length){event.preventDefault();deleteDialog.value.focus();return}const first=items[0],last=items[items.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===deleteDialog.value)){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}
watch(deleting,async value=>{await nextTick();if(value)deleteDialog.value?.focus();else if(deleteTrigger?.isConnected)deleteTrigger.focus();});
async function remove(){if(!deleting.value||busy.value)return;const source=deleting.value;await action(async()=>{const result=await api('/'+source.id,'DELETE',{});if(Number.isInteger(result.resources_deleted)&&Number.isInteger(result.nodes_deleted))deleteResult.value={resources:result.resources_deleted,nodes:result.nodes_deleted,shared:Number.isInteger(result.shared_resources_retained)?result.shared_resources_retained:0};rows.value=rows.value.filter(row=>row.source.id!==source.id);emit('loaded',rows.value);deleting.value=null;notice.value='订阅来源已删除';});}
let timer:ReturnType<typeof setTimeout>|undefined,alive=true;
async function poll(){if(!document.hidden&&!busy.value)await load();if(alive)timer=setTimeout(poll,rows.value.some(r=>r.running||r.source.queued)?5000:30000);}
onMounted(async()=>{await load();if(alive)timer=setTimeout(poll,5000)});onUnmounted(()=>{alive=false;loadRequest.cancel();clearTimeout(timer)});
</script>
<template><section :class="['source-page',{'source-embedded':embedded}]">
 <div :class="embedded?'resource-section-heading':'page-heading'"><div><h2 v-if="embedded">{{t('订阅来源')}}</h2><h1 v-else>{{t('订阅来源')}}</h1><p v-if="embedded">{{t('添加、更新和管理上游链接，出口自动归入订阅出口')}}</p></div><button class="primary" @click="edit()"><Plus :size="16"/>{{t('添加订阅来源')}}</button></div>
 <div v-if="!embedded" class="pool-intro"><Link2 :size="22"/><div><strong>{{t('上游订阅 → 私有 IP 池')}}</strong><p>{{t('集中管理导入的机场订阅；普通订阅和公共订阅用于向成员分发本站节点。')}}</p></div><span class="spacer"/><span class="badge neutral">{{t('每日错峰更新')}}</span></div>
 <p v-if="error&&!editing&&!deleting" class="error" role="alert">{{t(error)}}</p><p v-if="notice" class="settings-saved" role="status">{{t(notice)}}<template v-if="deleteResult"> · {{t('已删除出口')}} {{deleteResult.resources}} · {{t('已删除节点')}} {{deleteResult.nodes}}<span v-if="deleteResult.shared" class="source-delete-note">{{t('继续由其他来源管理的共享出口')}} {{deleteResult.shared}}</span><span class="source-delete-note">{{t('请更新客户端订阅，已删除节点将不再分发。')}}</span></template></p>
 <div class="source-summary"><span><Link2 :size="15"/>{{rows.length}} / 32 {{t('订阅来源')}}</span><span><Clock3 :size="15"/>{{t('默认每日一次 · 独立时段')}}</span><span><ShieldCheck :size="15"/>{{t('单任务执行 · 避开测速与公共采集')}}</span></div>
 <p v-if="!ready&&!error" class="source-loading" role="status">{{t('正在读取订阅来源…')}}</p>
 <div class="source-grid"><article v-for="row in rows" :key="row.source.id" class="source-card"><header><span class="source-symbol"><Link2 :size="20"/></span><div><h2>{{row.source.name}}</h2><code>{{row.source.address}}</code></div><span :class="['badge',row.running||row.source.queued?'neutral':row.source.error?'danger':row.source.enabled?'success':'neutral']">{{t(row.running?'更新中…':row.source.queued?'排队中':row.source.error?'更新失败':row.source.enabled?'自动更新':'已暂停')}}</span></header><div class="source-counts"><div><strong>{{row.resources}}</strong><span>{{t('当前资源')}}</span></div><div><strong>{{row.source.added||0}}</strong><span>{{t('上次新增')}}</span></div><div><strong>{{row.source.removed||0}}</strong><span>{{t('上次清理')}}</span></div></div><dl><div><dt>{{t('最近成功')}}</dt><dd>{{date(row.source.last_success)}}</dd></div><div><dt>{{t('下次自动更新')}}</dt><dd>{{row.source.enabled?date(row.source.next_at):t('已暂停')}}</dd></div></dl><p v-if="row.source.error" class="source-warning">{{t(row.source.error)}}</p><p v-if="row.stale" class="source-warning">{{row.stale}} {{t('项旧资源仍被使用或需保留，请核对后切换')}}</p><details v-if="row.source.warnings?.length"><summary>{{row.source.warnings.length}} {{t('项节点未能更新')}}</summary><p v-for="w in row.source.warnings" :key="w.index">#{{w.index}} · {{t(w.reason)}}</p></details><footer><button class="text-button" @click="emit('resources',row.resource_ids,row.source.name)"><Database :size="14"/>{{t('查看资源')}}</button><span class="spacer"/><button class="icon" :title="t('编辑订阅来源')" @click="edit(row.source)"><Pencil :size="15"/></button><button class="icon" :title="t('删除订阅来源')" :disabled="busy" @click="confirmDelete(row.source,$event)"><Trash2 :size="15"/></button><button :disabled="busy||row.running||row.source.queued" @click="refresh(row.source)"><RefreshCw :size="14" :class="{spin:row.running}"/>{{t('立即更新')}}</button></footer></article><div v-if="ready&&!rows.length" class="message-empty source-empty"><Link2 :size="34"/><h3>{{t('尚未添加订阅来源')}}</h3><p>{{t('添加 HTTPS 订阅链接后，后台自动同步到私有 IP 池')}}</p><button @click="edit()">{{t('添加订阅来源')}}</button></div></div>
 <details class="source-details"><summary>{{t('更新规则与资源保留')}}</summary><p class="source-footnote">{{t('各来源每天在独立时段更新，任务之间至少间隔 60 秒。失败后错峰退避重试，旧资源保留。上游配置改变时会新增资源；已绑定的旧资源标记待处理，避免自动切断业务。')}}</p><p class="source-footnote">{{t('手动删除来源会删除专属出口及绑定节点；共享出口仍归其他来源。自动更新时的资源保留规则不适用于删除来源。')}}</p></details>
 <Teleport to="body"><div v-if="editing||deleting" class="message-overlay" @click.self="closeDialog"><form v-if="editing" class="compose-card" role="dialog" aria-modal="true" :aria-label="t(form.id?'编辑订阅来源':'添加订阅来源')" @submit.prevent="save"><header><h2>{{t(form.id?'编辑订阅来源':'添加订阅来源')}}</h2><button type="button" class="icon" :aria-label="t('关闭')" @click="editing=false"><X :size="20"/></button></header><p v-if="error" class="error" role="alert">{{t(error)}}</p><label>{{t('订阅名称')}}<input v-model="form.name" :required="!!form.id" maxlength="80" :placeholder="t('例如：企业主线路')"/></label><label>{{t('上游订阅链接')}}<input v-model="form.url" type="password" autocomplete="off" :required="!form.id" maxlength="8192" :placeholder="form.id?t('留空保持现有链接'):'https://…'"/></label><label class="inline-check source-toggle"><input v-model="form.enabled" type="checkbox"/>{{t('每日自动更新')}}</label><p class="source-footnote">{{t('订阅地址加密保存，页面仅显示来源域名。首次导入和手动更新会进入同一后台队列。')}}</p><footer><button type="button" @click="editing=false">{{t('取消')}}</button><button class="primary" :disabled="busy">{{t('保存')}}</button></footer></form><section v-else-if="deleting" ref="deleteDialog" class="compose-card" role="dialog" aria-modal="true" :aria-label="t('删除订阅来源')" :aria-busy="busy" tabindex="-1" @keydown="deleteKeydown"><h2>{{t('删除订阅来源')}} · {{deleting.name}}</h2><p class="source-footnote">{{t('删除此来源、专属出口及绑定节点。共享出口继续由其他订阅来源管理，不会转入独立出口。此操作不可恢复，请更新客户端订阅。')}}</p><p v-if="error" class="error" role="alert">{{t(error)}}</p><footer><button :disabled="busy" @click="closeDialog">{{t('取消')}}</button><button class="danger-button" :disabled="busy" @click="remove"><LoaderCircle v-if="busy" :size="14" class="spin"/>{{busy?t('正在删除…'):t('删除来源及关联资源')}}</button></footer></section></div></Teleport>
</section></template>
<style>
.source-delete-note{display:block;margin-top:7px;font-size:11px;line-height:1.7}
.source-embedded .source-summary{margin:0 0 22px;padding:14px 17px;border:1px solid var(--border);background:var(--surface);border-radius:8px;gap:12px 22px}.source-details{margin:22px 0;color:var(--muted);font-size:11px;line-height:1.8}.source-details>summary{cursor:pointer}.source-details .source-footnote{margin:10px 0}.source-loading{padding:28px 0;color:var(--muted);font-size:12px}
.source-summary{display:flex;gap:24px;flex-wrap:wrap;margin:24px 0;font-size:11px;color:var(--muted)}.source-summary>span{display:flex;gap:7px;align-items:center}.source-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.source-card{border:1px solid var(--border);background:var(--surface);border-radius:10px;padding:24px;min-width:0}.source-card header{display:flex;align-items:center;gap:12px}.source-symbol{display:grid;place-items:center;width:40px;height:40px;background:var(--accent-soft);color:var(--accent-text);border-radius:10px;flex-shrink:0}.source-card h2{font-size:15px;margin:0 0 7px;overflow-wrap:anywhere}.source-card header>div{min-width:0;flex:1}.source-card code{font-size:10px;color:var(--muted);overflow-wrap:anywhere}.source-card header>.badge{font-size:10px;flex-shrink:0}.source-counts{display:grid;grid-template-columns:repeat(3,1fr);margin:23px 0;padding:20px 0;border-top:1px solid var(--border);border-bottom:1px solid var(--border)}.source-counts>div{display:flex;flex-direction:column;gap:7px}.source-counts strong{font-size:24px;font-weight:600}.source-counts span{font-size:10px;color:var(--muted)}.source-card dl{display:flex;flex-direction:column;gap:14px;font-size:11px}.source-card dl>div{display:flex;justify-content:space-between;gap:15px}.source-card dt{color:var(--muted)}.source-card dd{margin:0;text-align:right}.source-card footer{display:flex;align-items:center;gap:8px;margin-top:22px;padding-top:18px;border-top:1px solid var(--border)}.source-card footer button{font-size:11px}.source-warning{font-size:11px;line-height:1.7;color:#d6a96a;overflow-wrap:anywhere}.source-card details{font-size:11px;line-height:1.6;color:var(--muted)}.source-empty{grid-column:1/-1;border:1px dashed var(--border);border-radius:10px}.source-empty button{margin-top:22px}.source-footnote{font-size:11px;line-height:1.9;color:var(--muted);margin:22px 0}.compose-card .source-toggle{display:flex;flex-direction:row;align-items:center}.source-toggle input{width:15px;height:15px;min-height:15px}.quality-provider-list{border-top:1px solid var(--border);margin-top:18px;padding-top:18px}.quality-provider-list h3{font-size:13px;margin:0 0 14px}.quality-provider-list article{display:flex;gap:12px;align-items:flex-start;padding:12px 0;border-bottom:1px solid var(--border);font-size:11px}.quality-provider-list article>div{flex:1;display:flex;flex-direction:column;gap:6px;min-width:0}.quality-provider-list small{font-size:10px;color:var(--muted)}.quality-provider-list .provider-result{font-size:10px;color:var(--muted);overflow-wrap:anywhere}@media(max-width:1100px){.source-grid{grid-template-columns:1fr}}@media(max-width:650px){.source-card{padding:20px}.source-card footer{flex-wrap:wrap}.source-summary{gap:13px}.source-card header{flex-wrap:wrap}.source-card header>.badge{margin-left:52px}}
</style>
