import type { IPQuality } from "./quality";
import type { SubscriptionNode } from "./NodeSubscriptionCards.vue";
import type { SiteSettings } from "./PanelSettings.vue";

export type QuotaMeter = {period_id:string;start:number;end:number;pending_reset:boolean;upload:number;download:number;base_upload:number;base_download:number;raw_base_upload:number;raw_base_download:number};
export type Entitlement = {plan_id:string;version:number;name:string;group_ids:string[];cycle:string;timezone:string;assigned_at:number;revision:string};
export type Plan = {id:string;version:number;name:string;description:string;category:string;notes:string;archived:boolean;sort:number;quota:number;valid_days:number;cycle:string;timezone:string;group_ids:string[];vless:boolean;hy2:boolean};
export type NodeGroup = {id:string;name:string;description:string;scope:'private'|'public';enabled:boolean;sort:number;revision:string};
export type GroupMember = {site_id:string;node_id:string;name:string;protocol:string};
export type User = {
  meter?:QuotaMeter;
  entitlement?:Entitlement;
  id: number;
  username: string;
  role: string;
  enabled: boolean;
  vless: boolean;
  hy2: boolean;
  expires: number;
  quota: number;
  upload: number;
  download: number;
  vless_traffic: number;
  hy2_traffic: number;
  created: number;
  last_sub: number;
};
export type SpeedResult = {
  at: number;
  latency_ms: number;
  mbps: number;
  bytes: number;
  partial: boolean;
  error?: string;
};
export type Node = {
 policy_version?:number;rate_milli?:number;rate_revision?:string;group_ids?:string[];
	default_direct?: boolean;
	reality_sni?: string;
  dns?: {mode: string; doh?: string; ipv6?: string};
	quality?: IPQuality;
	managed_by?: string;
  speed?: SpeedResult;
  upstream_type?: string;
  exit_id?: string;
  id: string;
  name: string;
  protocol: string;
  enabled: boolean;
  exit: string;
  host: string;
  port: number;
  username: string;
  password?: string;
  has_password: boolean;
  probe_ip: string;
  probed_at: number;
  country: string;
  country_code: string;
  checked_at: number;
  probe_error: string;
};
export type IPResource = Node & {
  subscription_id?: string;
  source_stale?: boolean;
	pool_group?: string;
	source?: string;
  label: string;
  notes: string;
  revision: string;
  reachable: boolean;
  node_ids: string[];
};
export type State = {
  runtime?: { mode: 'normal' | 'no_logs'; audit_enabled: boolean; traffic_history_enabled: boolean; subscription_access_enabled?: boolean };
  site: SiteSettings;
  unread_messages: number;
  me: User;
  users: User[];
  nodes: Node[];
  ip_pool: IPResource[];
  totals: { upload: number; download: number; active: number };
  system: {
    edition?: 'lite' | 'pro';
    site_id?: string;
    database?: string;
    cache?: string;
    cache_degraded?: boolean;
    version: string;
    uptime: number;
    heap: number;
    status: string;
    error: string;
    traffic_error: string;
    applied_at: number;
    panel_host: string;
    vless_host: string;
    hy2_host: string;
    reality_sni?: string;
    cert_expires: number;
    services?: { name: string; active: boolean }[];
  };
  history: { hour: number; upload: number; download: number }[];
  audit: { at: number; actor: string; action: string; target: string }[];
};
export type Sub = { url: string; raw: string; active: boolean; user: User; pool: "private" | "public"; nodes: SubscriptionNode[] };
