#!/usr/bin/env python3
"""Disposable installation tests; standalone PG recovery uses isolated random schemas."""
import hashlib
import json
import os
import secrets
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import install
import infrastructure
from nginx_proxy_integration import verify_wallet_proxy


def verify_postgres_schema_recovery(config, directory):
    """Exercise real pg_dump/restore in uniquely named, disposable schemas only."""
    suffix = secrets.token_hex(8)
    site = 'qa_restore_' + suffix
    schema, neighbor = 'gy_' + site, 'gy_qa_neighbor_' + suffix
    sentinel = 'qa_restore_sentinel_' + suffix
    fixture = {'site_id': site, 'database': dict(config['database'])}
    env = infrastructure.postgres_env(fixture)
    owned_schemas, owns_sentinel = [], False

    def command(*args, data=None, success=True):
        result = subprocess.run(args, env=env, input=data, capture_output=True)
        if success and result.returncode:
            # Connection parameters and server output must never reach CI logs.
            raise RuntimeError('PostgreSQL fixture command failed: ' + Path(args[0]).name)
        return result

    def sql(text):
        return command('psql', '-X', '-q', '-A', '-t', '-v', 'ON_ERROR_STOP=1',
                       '--file=-', data=text.encode()).stdout

    def fingerprint(*selection):
        dump = command('pg_dump', '--format=plain', '--no-owner', '--no-privileges', *selection).stdout
        # Recent PostgreSQL clients randomize \restrict keys. Object creation
        # ordering/OIDs are immaterial; all DDL, sequence state and data remain.
        lines = sorted(line for line in dump.splitlines()
                       if line and not line.startswith((b'--', b'\\restrict ', b'\\unrestrict ')))
        return hashlib.sha256(b'\n'.join(lines)).hexdigest()

    def unchanged(target, outside):
        assert fingerprint('--schema=' + schema) == target, 'failed restore changed the current site'
        assert fingerprint('--schema=' + neighbor) == outside[0], 'restore changed another site'
        assert fingerprint('--table=public.' + sentinel) == outside[1], 'restore changed public data'

    def expect_refusal(path):
        try:
            infrastructure.restore_postgres(fixture, path)
        except (ValueError, OSError, subprocess.CalledProcessError):
            return
        raise AssertionError('unsafe PostgreSQL recovery was not refused')

    try:
        # Do not reuse a configured site's schema, even when called against a
        # live database. Track ownership so cleanup never drops an existing name.
        for name in (schema, neighbor):
            sql('CREATE SCHEMA ' + name)
            owned_schemas.append(name)
        sql('CREATE TABLE public.' + sentinel + ' (id integer PRIMARY KEY, marker text NOT NULL)')
        owns_sentinel = True
        sql(f"""
CREATE TABLE {schema}.users (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username text UNIQUE NOT NULL);
CREATE TABLE {schema}.schema_migrations (version text PRIMARY KEY, checksum text NOT NULL, applied_at bigint NOT NULL);
CREATE TABLE {schema}.payloads (id integer PRIMARY KEY, value text NOT NULL);
CREATE INDEX users_name_prefix ON {schema}.users (lower(username));
INSERT INTO {schema}.users (username) VALUES ('original-owner'), ('original-member');
INSERT INTO {schema}.schema_migrations VALUES ('001_base.sql', 'old-checksum', 1);
INSERT INTO {schema}.payloads SELECT n, md5(n::text) || md5((n+1000)::text) FROM generate_series(1,512) n;
CREATE TABLE {neighbor}.users (id integer PRIMARY KEY, username text NOT NULL);
INSERT INTO {neighbor}.users VALUES (1, 'other-site-unchanged');
INSERT INTO public.{sentinel} VALUES (1, 'public-unchanged');
""")
        original = fingerprint('--schema=' + schema)
        outside = (fingerprint('--schema=' + neighbor), fingerprint('--table=public.' + sentinel))
        backup = Path(directory) / (site + '.dump')
        infrastructure.dump_postgres(fixture, backup)
        sql(f"""
BEGIN;
CREATE TABLE {schema}.email_accounts (user_id bigint PRIMARY KEY REFERENCES {schema}.users(id), email text UNIQUE NOT NULL);
CREATE TABLE {schema}.payment_receipts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint REFERENCES {schema}.users(id), amount bigint NOT NULL);
ALTER TABLE {schema}.users ADD COLUMN after_migration boolean NOT NULL DEFAULT true;
INSERT INTO {schema}.email_accounts VALUES (1, 'fixture@example.invalid');
INSERT INTO {schema}.payment_receipts (user_id, amount) VALUES (1, 12345);
INSERT INTO {schema}.schema_migrations VALUES ('012_email_integration.sql', 'new-checksum', 2);
UPDATE {schema}.users SET username='mutated-after-migration-' || id;
INSERT INTO {schema}.users (username) VALUES ('new-user-after-backup');
COMMIT;
""")
        current = fingerprint('--schema=' + schema)
        assert current != original

        # Find the shortest readable TOC, then cut inside the following data.
        # Removing a fixed number of trailing bytes is insufficient: some
        # pg_dump versions append optional blocks that pg_restore never needs.
        damaged = Path(directory) / (site + '-truncated.dump')
        archive = backup.read_bytes()
        lower, upper = 0, len(archive)
        while lower < upper:
            middle = (lower + upper) // 2
            damaged.write_bytes(archive[:middle])
            if command('pg_restore', '--list', str(damaged), success=False).returncode == 0:
                upper = middle
            else:
                lower = middle + 1
        assert lower + 32 < len(archive), 'fixture has no table-data block after its archive TOC'
        damaged.write_bytes(archive[:lower + 32])
        command('pg_restore', '--list', str(damaged))
        assert command('pg_restore', '--exit-on-error', '--file=' + os.devnull,
                       str(damaged), success=False).returncode != 0, 'damaged fixture still decodes successfully'
        expect_refusal(damaged)
        unchanged(current, outside)
        print('PASS damaged PostgreSQL archive preserves current schema and data')

        for dependency in ('foreign-key', 'view'):
            if dependency == 'foreign-key':
                sql(f'CREATE TABLE {neighbor}.external_dependency (user_id bigint REFERENCES {schema}.users(id)); INSERT INTO {neighbor}.external_dependency VALUES (1)')
                cleanup = f'DROP TABLE {neighbor}.external_dependency'
            else:
                sql(f'CREATE VIEW {neighbor}.external_dependency AS SELECT id, username FROM {schema}.users')
                cleanup = f'DROP VIEW {neighbor}.external_dependency'
            with_dependency = (fingerprint('--schema=' + neighbor), outside[1])
            expect_refusal(backup)
            unchanged(current, with_dependency)
            sql(cleanup)
        print('PASS external PostgreSQL foreign keys and views refuse recovery atomically')

        # This object is intentionally absent from the old archive. Table drops
        # succeed first, then DROP SCHEMA RESTRICT must fail on the function and
        # roll back all prior DDL/data changes in the same server transaction.
        sql(f"CREATE FUNCTION {schema}.ci_recovery_guard() RETURNS integer LANGUAGE sql AS 'SELECT 7'")
        with_function = fingerprint('--schema=' + schema)
        assert with_function != current
        expect_refusal(backup)
        unchanged(with_function, outside)
        sql(f'DROP FUNCTION {schema}.ci_recovery_guard()')
        unchanged(current, outside)
        print('PASS late PostgreSQL recovery failure rolls back earlier table drops and preserves data')

        infrastructure.restore_postgres(fixture, backup)
        unchanged(original, outside)
        print('PASS old PostgreSQL snapshot restores complete schema/data and preserves neighboring site/public')
    finally:
        cleanup_failed = False
        cleanup_queries = []
        if owns_sentinel:
            cleanup_queries.append('DROP TABLE public.' + sentinel)
        for name in reversed(owned_schemas):
            cleanup_queries.append('DROP SCHEMA ' + name + ' CASCADE')
        for query in cleanup_queries:
            result = command('psql', '-X', '-q', '-v', 'ON_ERROR_STOP=1', '--file=-',
                             data=query.encode(), success=False)
            cleanup_failed = cleanup_failed or result.returncode != 0
        if cleanup_failed:
            raise RuntimeError('PostgreSQL fixture cleanup failed for generated suffix ' + suffix)


if sys.argv[1:2] == ['--postgres-recovery-only']:
    if len(sys.argv) != 3:
        raise SystemExit('Usage: integration.py --postgres-recovery-only PRIVATE_CONFIG_JSON')
    with tempfile.TemporaryDirectory(prefix='guangyue-pg-recovery-') as fixture_directory:
        verify_postgres_schema_recovery(json.loads(Path(sys.argv[2]).read_text()), fixture_directory)
    raise SystemExit(0)

if os.geteuid() != 0 or os.environ.get('GITHUB_ACTIONS') != 'true':
    raise SystemExit('This integration harness is restricted to disposable GitHub Actions runners.')
if os.environ.get('GY_INTEGRATION_EDITION') in ('business','business-lite'):
    os.execv(sys.executable,[sys.executable,str(Path(__file__).with_name('business_integration.py')),*sys.argv[1:]])
if os.environ.get('GY_INTEGRATION_EDITION','').startswith('updater-'):
    os.environ['GY_INTEGRATION_EDITION']=os.environ['GY_INTEGRATION_EDITION'].removeprefix('updater-')
    os.execv(sys.executable,[sys.executable,str(Path(__file__).with_name('update_integration.py')),*sys.argv[1:]])
bundle = Path(sys.argv[1]).resolve()
temp = Path(tempfile.mkdtemp(prefix='guangyue-integration-'))
os.chmod(temp, 0o700)
cert, key = temp / 'fullchain.pem', temp / 'privkey.pem'


def run(*args, success=True):
    p = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if success and p.returncode:
        # Never print a command's output: it may contain ephemeral credentials.
        safe=[line for line in p.stderr.decode(errors='replace').splitlines() if line.startswith(('Installation failed:','Upgrade failed:','Infrastructure setup failed:'))]
        detail=('; '+safe[-1][:300]) if safe else ''
        raise RuntimeError('command failed: ' + Path(args[0]).name + ' exit=' + str(p.returncode)+detail)
    return p


def newcert():
    run('openssl', 'req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '3', '-subj', '/CN=panel.example.com', '-addext', 'subjectAltName=DNS:panel.example.com,DNS:node.example.com', '-keyout', str(key), '-out', str(cert))


def api(path, data=None, cookie=''):
    headers = {'X-Requested-With': 'guangyue', 'Content-Type': 'application/json'}
    if cookie:
        headers['Cookie'] = cookie
    request = urllib.request.Request('http://127.0.0.1:19100' + path, data=json.dumps(data).encode() if data is not None else None, headers=headers)
    with urllib.request.build_opener(urllib.request.ProxyHandler({})).open(request, timeout=15) as response:
        return json.load(response), response.headers.get('Set-Cookie', '').split(';')[0]


def post_migration_fault_bundle(source):
    """A real -prepare followed by a committed new migration and a forced fault."""
    target = temp / 'post-migration-fault-bundle'
    shutil.copytree(source, target)
    shutil.copyfile(source / 'bin/guangyue-linux-amd64', target / 'deploy/ci-good-panel')
    wrapper = '''#!/usr/bin/python3
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
sys.dont_write_bytecode = True
sys.path.insert(0, '/opt/guangyue-personal/deploy')
from infrastructure import postgres_env
if sys.argv[1:] != ['-prepare']:
    raise SystemExit(43)
state = Path('/var/lib/guangyue')
fd, name = tempfile.mkstemp(prefix='ci-good-panel-', dir=state)
os.close(fd)
try:
    shutil.copyfile('/opt/guangyue-personal/deploy/ci-good-panel', name)
    os.chmod(name, 0o700)
    subprocess.run([name, '-prepare'], capture_output=True, check=True)
finally:
    os.unlink(name)
config = json.loads(Path('/etc/guangyue-personal.json').read_text())
schema = 'gy_' + config['site_id']
sql = f"""
BEGIN;
CREATE TABLE {schema}.ci_after_migration_accounts (user_id bigint PRIMARY KEY REFERENCES {schema}.users(id), marker text NOT NULL);
INSERT INTO {schema}.ci_after_migration_accounts SELECT id, 'new-foreign-key' FROM {schema}.users;
UPDATE {schema}.users SET username=username || '-ci-fault';
UPDATE {schema}.schema_migrations SET checksum='ci-fault-' || checksum WHERE version=(SELECT min(version) FROM {schema}.schema_migrations);
INSERT INTO {schema}.schema_migrations VALUES ('999_ci_after_prepare.sql', 'ci-committed-migration', 1);
COMMIT;
"""
subprocess.run(['psql', '-X', '-v', 'ON_ERROR_STOP=1', '--file=-'], input=sql.encode(), env=postgres_env(config), capture_output=True, check=True)
(state / 'ci-migration-completed.json').write_text(json.dumps({'prepare_completed': True, 'migration_committed': True}))
raise SystemExit(42)
'''
    (target / 'bin/guangyue-linux-amd64').write_text(wrapper)
    rows = [hashlib.sha256(path.read_bytes()).hexdigest() + '  ' + path.relative_to(target).as_posix()
            for path in sorted(target.rglob('*')) if path.is_file() and path.name != 'SHA256SUMS']
    (target / 'SHA256SUMS').write_text('\n'.join(rows) + '\n')
    return target


try:
    newcert()
    command = [sys.executable, str(bundle / 'deploy/install.py'), '--bundle', str(bundle), '--panel-domain', 'panel.example.com', '--node-domain', 'node.example.com', '--cert', str(cert), '--key', str(key)]
    edition=os.environ.get('GY_INTEGRATION_EDITION','lite')
    if edition=='pro':
        run(sys.executable,str(bundle/'deploy/infrastructure.py'),'--apply')
        command+=['--edition','pro','--site-id','ci_pro','--infrastructure-file',str(infrastructure.PROFILE)]
    if edition=='lite': command+=['--role','standalone']
    run(*command)
    assert not install.CONFIG.exists(), 'preflight wrote production config'
    run(*command, '--apply')
    install.health()
    assert install.STATE.stat().st_mode & 0o777 == 0o700
    assert Path('/run/guangyue-reality').stat().st_mode & 0o7777 == 0o2750
    run('curl', '-fsS', '--noproxy', '*', '--cacert', str(cert), '--resolve', 'panel.example.com:443:127.0.0.1', 'https://panel.example.com/api/health')
    verify_wallet_proxy(cert)
    initial = json.loads((install.STATE / 'initial-owner.json').read_text())
    _, cookie = api('/api/login', initial)
    state, _ = api('/api/subscription', cookie=cookie)
    assert {n['protocol'] for n in state['nodes']} == {'vless', 'hy2'}
    public, _ = api('/api/subscription?pool=public', cookie=cookie)
    assert not public['nodes'] and public['url'] != state['url']
    print('PASS fresh install, service health, real Nginx HTTPS, private permissions and subscription separation')

    network, _ = api('/api/network-settings', cookie=cookie)
    assert network['desired'] == {'bbr': True, 'hy2': True}
    assert network['actual']['bbr'] and network['actual']['hy2'] and network['actual']['hy2_running']
    assert int(network['actual']['rmem_max']) >= 8 << 20
    baseline = json.loads(Path('/var/lib/guangyue-updater/network.json').read_text())['original']
    for enabled in [False, True]:
        api('/api/network-settings', {'bbr': enabled, 'hy2': enabled, 'revision': network['revision']}, cookie)
        deadline = time.monotonic() + 75
        while time.monotonic() < deadline:
            try:
                network, _ = api('/api/network-settings', cookie=cookie)
                if network['operation']['stage'] in ['succeeded', 'failed']: break
            except OSError: pass  # The panel reconnects during a HY profile change.
            time.sleep(1)
        assert network['operation']['stage'] == 'succeeded', network['operation'].get('error')
        assert network['desired'] == {'bbr': enabled, 'hy2': enabled}
        assert network['actual']['hy2'] == enabled and network['actual']['hy2_running']
        if not enabled:
            assert network['actual']['congestion_control'] == baseline['net.ipv4.tcp_congestion_control']
            assert network['actual']['rmem_max'] == baseline['net.core.rmem_max']
    after_network, _ = api('/api/subscription', cookie=cookie)
    assert after_network['url'] == state['url']
    print('PASS default BBR/HY2, real privileged toggle off/on, restoration and preserved subscription')

    from entitlement_integration import verify_entitlements
    verify_entitlements(bundle, temp, cert, api, cookie, initial["password"])

    # Occupied paths must refuse a second install, without touching current data.
    assert run(*command, '--apply', success=False).returncode != 0
    install.health()
    print('PASS existing deployment refusal')

    cert_script = str(install.APP / 'deploy/certificates.py')
    old_hash = hashlib.sha256(Path('/etc/nginx/guangyue-tls/current/fullchain.pem').read_bytes()).hexdigest()
    original_key = key.read_bytes()
    run('openssl', 'genrsa', '-out', str(key), '2048')
    assert run(sys.executable, cert_script, success=False).returncode != 0
    assert hashlib.sha256(Path('/etc/nginx/guangyue-tls/current/fullchain.pem').read_bytes()).hexdigest() == old_hash
    key.write_bytes(original_key)
    newcert()
    run(sys.executable, cert_script)
    assert hashlib.sha256(Path('/etc/nginx/guangyue-tls/current/fullchain.pem').read_bytes()).hexdigest() != old_hash
    run('curl', '-fsS', '--noproxy', '*', '--cacert', str(cert), '--resolve', 'panel.example.com:443:127.0.0.1', 'https://panel.example.com/api/health')
    print('PASS certificate mismatch rejection and real renewal/reload')

    run(sys.executable, str(bundle / 'deploy/upgrade.py'), '--bundle', str(bundle), '--apply')
    install.health()
    verify_wallet_proxy(cert)
    print('PASS offline backup and successful upgrade')

    # A checksum-consistent release whose executable fails must trigger rollback.
    bad = temp / 'fault-bundle'
    shutil.copytree(bundle, bad)
    (bad / 'bin/guangyue-linux-amd64').write_text('#!/bin/sh\nexit 42\n')
    lines = []
    for row in (bad / 'SHA256SUMS').read_text().splitlines():
        _, name = row.split('  ', 1)
        lines.append(hashlib.sha256((bad / name).read_bytes()).hexdigest() + '  ' + name)
    (bad / 'SHA256SUMS').write_text('\n'.join(lines) + '\n')
    assert run(sys.executable, str(bundle / 'deploy/upgrade.py'), '--bundle', str(bad), '--apply', success=False).returncode != 0
    assert any(p.read_bytes() == b'#!/bin/sh\nexit 42\n' for p in Path('/root/guangyue-backups').glob('upgrade-*/failed-app/bin/guangyue')), 'fault did not reach rollback'
    install.health()
    _, cookie = api('/api/login', initial)
    restored, _ = api('/api/subscription', cookie=cookie)
    assert sorted(n['uri'] for n in restored['nodes']) == sorted(n['uri'] for n in state['nodes']), 'rollback changed credentials'
    print('PASS failed executable rollback and credential preservation')
    if edition=='lite':
        run(sys.executable,str(bundle/'deploy/infrastructure.py'),'--apply')
        run(sys.executable,str(bundle/'deploy/upgrade.py'),'--bundle',str(bundle),'--edition','pro','--site-id','ci_migrated','--infrastructure-file',str(infrastructure.PROFILE),'--apply')
        install.health()
        _,cookie=api('/api/login',initial)
        migrated,_=api('/api/subscription',cookie=cookie)
        assert sorted(n['uri'] for n in migrated['nodes'])==sorted(n['uri'] for n in state['nodes'])
        print('PASS Lite to Pro migration preserves live subscription URIs')
    health,_=api('/api/health');assert health['edition']=='pro'
    run(sys.executable,str(bundle/'deploy/upgrade.py'),'--bundle',str(bundle),'--apply')
    pro_config = json.loads(install.CONFIG.read_text())
    verify_postgres_schema_recovery(pro_config, temp)

    def pro_query(query):
        result = subprocess.run(['psql', '-X', '-q', '-A', '-t', '-v', 'ON_ERROR_STOP=1', '--file=-'],
                                input=query.encode(), env=infrastructure.postgres_env(pro_config), capture_output=True)
        assert result.returncode == 0, 'Pro rollback verification query failed'
        return result.stdout

    pro_schema = 'gy_' + pro_config['site_id']
    stable_rows = f'SELECT username FROM {pro_schema}.users ORDER BY id; SELECT version, checksum, applied_at FROM {pro_schema}.schema_migrations ORDER BY version;'
    before_migration = pro_query(stable_rows)
    migrated_bad = post_migration_fault_bundle(bundle)
    assert run(sys.executable,str(bundle/'deploy/upgrade.py'),'--bundle',str(migrated_bad),'--apply',success=False).returncode!=0
    markers = list(Path('/root/guangyue-backups').glob('upgrade-*/failed-state/ci-migration-completed.json'))
    assert any(json.loads(path.read_text()) == {'prepare_completed': True, 'migration_committed': True} for path in markers), 'upgrade did not fail after a committed migration'
    assert pro_query(stable_rows) == before_migration, 'Pro rollback retained post-migration data or checksums'
    assert pro_query(f"SELECT to_regclass('{pro_schema}.ci_after_migration_accounts') IS NULL") == b't\n', 'Pro rollback retained a new foreign-key table'
    install.health()
    _,cookie=api('/api/login',initial)
    restored,_=api('/api/subscription',cookie=cookie)
    assert sorted(n['uri'] for n in restored['nodes'])==sorted(n['uri'] for n in state['nodes'])
    assert list(Path('/root/guangyue-backups').glob('upgrade-*/postgres.dump'))
    print('PASS Pro failure after completed prepare/migration, full PostgreSQL rollback and credential preservation')

finally:
    # Runner is ephemeral; stop only our services. Do not emit or upload state.
    subprocess.run(['systemctl', 'stop', *install.UNITS], capture_output=True)
    shutil.rmtree(temp)
