import {describe,it,expect,vi,afterEach} from 'vitest';
import {invoiceOperationID,clearInvoiceOperation,tokenAmount,tokenAtoms,invoiceStateText,invoiceCanPay,invoiceQR,supportsPaymentPurpose,type CryptoInvoice} from './cryptoPayments';
const invoice={address:'0x9858EfFD232B4033E47d90003D41EC34EcaEda94',qr_uri:'ethereum:0xToken@1/transfer?address=0xRecipient&uint256=1230000',state:'waiting',order_state:'pending',expires:200} as CryptoInvoice;
describe('crypto amounts',()=>{
 it('preserves huge balances and 18-decimal dust exactly',()=>{expect(tokenAmount('900719925474099312345678901234567890',18)).toBe('900719925474099312.34567890123456789');expect(tokenAmount('1',18)).toBe('0.000000000000000001');expect(tokenAmount('1000000',6,2)).toBe('1.00');expect(tokenAtoms('900719925474099312.34567890123456789',18)).toBe('900719925474099312345678901234567890')});
 it('rejects exponent, sign, overprecision and invalid server amounts',()=>{for(const value of ['1e6','-1','1.0000001','01','NaN'])expect(()=>tokenAtoms(value,6)).toThrow();expect(()=>tokenAtoms('1.1',0)).toThrow();expect(tokenAmount('NaN',18)).toBe('—');expect(tokenAtoms('0',18)).toBe('0')});
});
it('payment completion depends on entitlement; late overpayment cannot replace active plan status',()=>{expect(invoiceStateText({...invoice,state:'review_required',order_state:'completed'})).toBe('套餐已生效');expect(invoiceStateText({...invoice,state:'paid'})).toBe('已到账，正在开通');expect(invoiceCanPay(invoice,100)).toBe(true);expect(invoiceCanPay(invoice,200)).toBe(false);expect(invoiceCanPay({...invoice,state:'confirming'},100)).toBe(false)});
it('exchange QR contains only address and wallet QR comes from frozen invoice',()=>{expect(invoiceQR(invoice,'exchange')).toBe(invoice.address);expect(invoiceQR(invoice,'wallet')).toBe(invoice.qr_uri);expect(invoiceQR({...invoice,qr_uri:'https://evil.test'},'wallet')).toBe('')});
it('crypto is excluded from fiat topups even if an older response omits purposes',()=>{expect(supportsPaymentPurpose({code:'crypto'},'topup')).toBe(false);expect(supportsPaymentPurpose({code:'evm_crypto'},'topup')).toBe(false);expect(supportsPaymentPurpose({code:'crypto',purposes:['order']},'topup')).toBe(false);expect(supportsPaymentPurpose({code:'epay'},'topup')).toBe(true)});

afterEach(()=>vi.unstubAllGlobals());
it('restores an uncertain invoice operation after reload without storing passwords or quotes',()=>{const values=new Map<string,string>();vi.stubGlobal('sessionStorage',{getItem:(k:string)=>values.get(k),setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)});const generate=vi.fn(()=> 'operation-1234567890');expect(invoiceOperationID('order','ethereum-usdt',generate)).toBe('operation-1234567890');expect(invoiceOperationID('order','ethereum-usdt',()=> 'another-operation-123')).toBe('operation-1234567890');expect(JSON.parse([...values.values()][0]!)).toEqual({asset_id:'ethereum-usdt',id:'operation-1234567890'});clearInvoiceOperation('order');expect(values.size).toBe(0)});
