package controlplane

import (
	"os"
	"testing"
)

// Run the same externally visible business invariants against real PostgreSQL.
// SQLite trigger fault-injection tests remain in the normal Lite suite.
func TestPostgresBehaviors(t *testing.T) {
	if os.Getenv("GY_TEST_POSTGRES_DSN") == "" {
		t.Skip("PostgreSQL integration not configured")
	}
	for _, v := range []struct {
		name string
		run  func(*testing.T)
	}{
		{"payment_module_takeover", TestPaymentModuleTakeoverDefaultsAndLocalOverride},
		{"payment_module_history", TestPaymentModuleBlocksIntentsButSettlesExistingFunds},
		{"payment_module_sweep", TestPaymentModuleKeepsApprovedSweep},
		{"crypto_payment_wrong_network", TestCryptoPaymentWrongNetworkIsRecordedForReview},
		{"crypto_payment_freeze_fulfillment", TestCryptoPaymentFreezeBlocksConfirmationAndProvisioning},
		{"crypto_payment_timely", TestCryptoPaymentTimelyBlockAfterDeadlineAndDisabledConfiguration},
		{"crypto_invoice_free", TestCryptoInvoiceFreeOrderAndWalletRecoveryGate},
		{"crypto_payment_partial", TestCryptoPaymentPartialFinalityAndExactlyOnceFulfillment},
		{"crypto_payment_late", TestCryptoPaymentLateCancelledAndMissingReceiptStayUncredited},
		{"crypto_payment_reorg", TestCryptoPaymentReorgReindexesAcrossInvoicesWithoutDoubleCredit},
		{"crypto_payment_freeze", TestCryptoPaymentFinalityViolationFreezesWholeChain},
		{"crypto_invoice_concurrency", TestCryptoInvoiceConcurrentAllocationAndRestart},
		{"crypto_sweep_durable", TestCryptoSweepDurableGasConfirmationAndRestart},
		{"crypto_sweep_concurrency", TestCryptoSweepConcurrentCreateLeaseAndCancel},
		{"crypto_sweep_constraints", TestCryptoSweepPreviewConstraintsAndFrozenChain},
		{"crypto_sweep_evidence", TestCryptoSweepRevertedAndTamperedEvidence},
		{"crypto_sweep_integrity", TestCryptoSweepIntegrityAndSnapshot},
		{"crypto_sweep_integrity_legacy", TestCryptoSweepIntegrityLegacyWalletAndCancelledFailure},
		{"crypto_wallet_permissions", TestCryptoWalletPermissionsSecretsAndBackup},
		{"crypto_wallet_dedup", TestCryptoWalletCanonicalDedupAndValidation},
		{"crypto_wallet_concurrency", TestCryptoWalletIndependentInstancesReplayAndRestart},
		{"crypto_wallet_restore", TestCryptoWalletRestoreHighWaterAndRecoveryGate},
		{"crypto_wallet_snapshot", TestCryptoWalletSnapshotIntegrityAndPagination},
		{"payment_topup_dedup", TestPaymentTopupDedupAcrossInstancesAndMethods},
		{"payment_late_refund", TestPaymentLateMismatchAndManualRefund},
		{"payment_order_recovery", TestPaymentOrderRecoveryCancellationAndRefundTruth},
		{"payment_provider_snapshot", TestPaymentProviderLifecycleAndSnapshot},
		{"payment_stripe", TestStripeCheckoutWebhookTopupAndRefund},
		{"payment_concurrent_recovery", TestPaymentOrderRecoveryConcurrentAndAfterExpiry},
		{"payment_checkout_replay", TestPaymentCheckoutReplayAndEventIdentity},
		{"payment_legacy_recovery", TestPaymentLegacyPaidRecoveryAndFailedActivation},
		{"payment_extra_charge", TestPaymentUnknownAndDuplicateChargeReview},
		{"integration_snapshot", TestIntegrationsSnapshotPreservesMailAndPaymentRecovery},
		{"integration_ciphertext", TestIntegrationsRestoreRejectsDamagedMailCiphertext},
		{"email_settings", TestEmailSettingsPermissionsCASAndWriteOnlyPassword},
		{"email_binding_reset", TestEmailBindingVerificationAndResetOneTime},
		{"email_registration", TestEmailRegistrationProofAtomicityAndRequiredEmail},
		{"email_queue_lease", TestEmailOutboxLeaseAndBoundedRetries},
		{"email_event_atomicity", TestEmailCommerceEventCaptureAtomicAndIdempotent},
		{"email_concurrent_settings", TestEmailConcurrentConfigurationDoesNotOverwrite},
		{"email_recipient_change", TestEmailOrderNotificationRechecksRecipient},
		{"commerce_snapshot", TestCommerceSnapshotRoundTrip},
		{"commerce_recovery", TestCommerceRecoveryAndRenewal},
		{"commerce_integrity", TestCommerceIntegrityAndArchive},
		{"commerce_images", TestSupportInternalImagesAndRetention},
		{"commerce_redemption", TestCommerceRedemptionAtomicAndRevocation},
		{"commerce_orders", TestCommerceOrderCaptureResetAndRefund},
		{"commerce_order_list", TestCommerceOrderListFirstPageReturnsNewOrder},
		{"commerce_mount_purchase", TestPurchaseReallocatesOldMountBudgetsAndExhaustionRevokes},
		{"commerce_mount_renewal", TestRenewalDoesNotRejectOldReservations},
		{"commerce_cancellation", TestCommerceCancellationIsolationAndExpiry},
		{"commerce_support", TestSupportTicketImagesAndOwnership},
		{"business_lifecycle", TestBusinessLifecycle},
		{"direct_subsites", TestDirectSubsiteLifecycle},
		{"mounted_isolation", TestMountedNodeIsolationAndSubscriptions},
		{"mounted_accounting", TestMountedAccountingRevocationAndPeriods},
		{"mounted_sharing", TestMountedTokenSharingAndLease},
		{"subsite_default_group", TestFixedGroupsUpgradeRemovesCustomGroupsWithoutWideningAccess},
		{"mounted_auto_access", TestAutomaticMountFollowsMainGroupsAndRevokes},
		{"mounted_auto_budget", TestAutomaticMountBudgetsRespectOtherSitesAndOfflineReservations},
		{"mounted_auto_compatibility", TestAutomaticMountManualCompatibilityAndInactiveUsers},
		{"offline_directory", TestLegacyOfflineDirectoryMigration},
		{"site_removal", TestRemovedLegacySiteRetainsUnsettledAccounting},
		{"site_policy_conversion", TestConvertedPoliciesPreserveNodeAccess},
		{"site_identity", TestMultipleDefaultSitesAndSelfImport},
		{"subsite_permissions", TestMasterControlsLiteSubsitePermissions},
		{"weighted_business", TestBusinessWeightedQuotasSparseAcknowledgementAndReset},
		{"business_membership_deletion", TestBusinessExitDeletionCleansGroupsAndRestoresOnFailure},
		{"entitlements", TestEntitlementSnapshotsRenewResetAndAccess},
		{"direct_node_access", TestIndependentNodeAccessAndPlanAuthority},
		{"plan_mount_access", TestPlanMountAccessWithoutUserAssignment},
		{"direct_node_validation", TestDirectNodeAccessPreviewAndAuthorization},
		{"direct_node_mounts", TestDirectNodeAccessMountsBothProtocolsAndRevokes},
		{"group_member_identity", TestNodeGroupMembersDistinguishProtocolAndSite},
		{"entitlement_migration", TestEntitlementMigrationAndUsageIsolation},
		{"entitlement_edit", TestRejectedEntitlementEditPreservesSessionsAndNewUserMeter},
		{"node_rates", TestNodeMeterRatesChangeDeletionAndNoLogs},
		{"membership_deletion", TestNodeDeleteRemovesGroupAndPreservesUsage},
		{"business_quota", TestBusinessAllocationsAndCounterRollback},
		{"shared_quality", TestDirectQualitySharedAcrossProtocols},
		{"authentication", TestUserIsolationAndCSRF},
		{"navigation_partial_save", TestPanelNavigationPartialSaveAndRevisions},
		{"navigation_concurrent", TestPanelNavigationConcurrentWriters},
		{"traffic_checkpoints", TestTrafficCheckpointRestartAndQuota},
		{"no_logs_accounting", TestRuntimeNoLogsPreservesAccountingAndExistingHistory},
		{"subscription_rotation", TestSubscriptionsAndCredentialRotation},
		{"pool_encryption", TestPoolAuthorizationEncryptionAndDuplicateProtection},
		{"source_cascade", TestSourceDeletionCascadesOwnedExitsNodesAndCredentials},
		{"shared_ownership", TestSourceDeletionReassignsSharedOwnershipWithoutManualConversion},
		{"subscription_isolation", TestPrivateAndPublicSubscriptionsHaveIndependentURLsContentsAndRotation},
		{"message_isolation", TestMessageRecipientIsolationAndReadState},
		{"default_nodes", TestDefaultDirectAPIRejectsDeletionDisableAndRebinding},
		{"multiple_hy2", TestMultipleHY2NodesDefaultDirectAndIndependentCredentials},
		{"node_save_receipts", TestNodeSaveReceiptReplay},
		{"node_save_rollback", TestNodeSaveReceiptRollbackAndValidation},
		{"node_save_concurrent", TestConcurrentNodeCreationUsesOneReceipt},
		{"stale_subscription", TestPartialAndInvalidSourceResponseDoesNotPrune},
	} {
		t.Run(v.name, v.run)
	}
}
